### ISSUE TITLE
[Bug] auto quest having some odd behaviour

### ISSUE THREAD

**Issue by rubyirisu** [Ephenia/Pokeclicker-Scripts#146]
![asdasdasd](https://user-images.githubusercontent.com/107065250/172438872-2e4d348f-317c-4a4b-8771-b9772a98dbad.png)
![asddddd](https://user-images.githubusercontent.com/107065250/172439013-822df327-1666-4881-85d4-c348d2173c62.png)
![image](https://user-images.githubusercontent.com/107065250/172439208-974de9dd-de19-454e-9570-a305618fb38b.png)
I am unable to have all quests active with auto quest, every time I refresh two or more of the quests are not taken, I am able to pick up the quests but it'll drop another one. I am using every module except for protein.

**Comment by Sorrow81** [comment]
To activate the quests you have to click on the quests you want in the modal (not on start, on the quest)

https://github.com/Ephenia/Pokeclicker-Scripts/blob/206981fa9b42e72fef785a79f66332a8de239ef6/README.md#custom-auto-quest-completer-autoquestcompleteruserjs
![questmodal](https://camo.githubusercontent.com/c467ff381d3f51d754e4aab57e293051e414fd2e227aac9c8b9d45ea2663ac9a/68747470733a2f2f692e696d6775722e636f6d2f63644f584157552e706e67)

**Comment by rubyirisu** [comment]
Yes that was the problem thank you.
