### ISSUE TITLE
V0.9.6 Pokerus fix?

### ISSUE THREAD

**Issue by Xross98** [Ephenia/Pokeclicker-Scripts#156]
Pokerus only spreads from your original Kanto starter, hopefully there's a way to change this to spreading from any Pokemon that have it please?

**Comment by Ephenia** [comment]
👀

**Comment by Mega-Rayquaza-8121** [comment]
oh yeah that would make it so much faster holy crap

**Comment by Dionisos94** [comment]
Maybe a normal script that would take your starter and breed it with only non-pokerused pokemon
And a custom that would "cheat" and give the ability to transfer the virus to any infected pokemon

**Comment by Ephenia** [comment]
There's a script now for fixing up Pokérus which is available now as of commit 1b6ea8ea867fc9818c6296eab1d318cbe50cc7f1

I think it's fair to call it a fix, albeit not the most balanced, but more true to Pokérus in the core series games with how it's supposed to work or what you'd just expect.
