### ISSUE TITLE
commit `Implement Quick Dungeons Select` seems to have broken the desktop version of `additionalvisualsettings`

### ISSUE THREAD

**Issue by JourneyOver** [Ephenia/Pokeclicker-Scripts#163]
ended up leaving a comment on the commit, but thought I should throw up an issue about it as well. Upon updating scripts, the latest version of `additionalvisualsettings` seems to be broken and no longer loading in the desktop version of the game.

If I go and put it in the `scripts` folder and change it back to the older version it seems to work again, but obviously I end up missing the reason for the update.

I'm just wondering if you are just no longer supporting the desktop version? as there are a couple scripts as of recent that just don't work in the desktop version at all.

Script that don't show up in desktop version are as followed:
additionalvisualsettings (broken within recent commit)
catchfilterfantasia
perkypokeruspandemic

**Comment by Erwanito92** [comment]
I can confirm that there is problems with some newer scripts.

The last additionalvisualsettings is just broken. It doesn't load, OR it loads but other scripts don't. Seems to be random on every reload of the desktop app.

Some goes for catchfilterfantasia. Sometimes it just load alone, or 99% of the time it doesn't load at all. (and even before the last additionalvisualsettings update)

Also, perkypokeruspandemic seems to never load.

**Comment by JourneyOver** [comment]
Haven't had the issue it loading but not other scripts loading for any of them, the ones I mentioned just outright refuse to load anymore.

From what I can tell it's something to do with a `var` to `const` change, because if I put them into the `scripts` folder and do a rename for every `const` to be `var` instead it works perfectly and loads, same with the other two scripts (changing all `const` to `var).

**Comment by Ephenia** [comment]
About where things are currently with Desktop support: https://github.com/Ephenia/Pokeclicker-Scripts/issues/158#issuecomment-1167823338 (well thought I'd include this in for transparency)

As for the changes being mentioned, I suspect it's maybe the changes being done to the initialization portion (unable to test these myself atm and hadn't prior).

Try reverting just this portion of the script and keep the rest of the variable declaration (const & let) changes throughout the rest of the script:
![image](https://user-images.githubusercontent.com/26987203/176575361-5d25e3a5-67b0-44e7-a68a-f72d318086b2.png)

If this is the issue I can revert it in the next revision being worked on at the moment, and changing this in a few other scripts where it may be problematic.

**Comment by JourneyOver** [comment]
@Ephenia Yep that's exactly it from the looks of things, as reverting that portion back to the previous revision seems to make things work and load correctly, can also confirm that it changing that partion in the other scripts that I mentioned above works as well.

**Comment by JourneyOver** [comment]
@Ephenia actually scratch that, it's causing other issues and idk why I didn't notice >.< for some reason or another it's now only loading a portion of the scripts. So many others just seem to disappear..

Going to test a bit more to see what is causing this new issue.

**Comment by JourneyOver** [comment]
Okay after a bit more testing I have found these things:

doing the above does work correctly but there seems to be more changes needed in at least the `additionalvisualsettings` script, from what I can tell I needed to change the
```
let checkWildPokeName;
let checkWildPokeDefeat;
let checkWildPokeImg;
let checkWildPokeHealth;
let checkWildPokeCatch;
let checkAllNotification;
const notificFunc = Notifier.notify;
let newSave;
let trainerCards;
```
to be
```
var checkWildPokeName;
var checkWildPokeDefeat;
var checkWildPokeImg;
var checkWildPokeHealth;
var checkWildPokeCatch;
var checkAllNotification;
const notificFunc = Notifier.notify;
var newSave;
var trainerCards;
```
to actually make it work and stop the whole other scripts randomly disappearing act also seems that only needing to change the `const scriptName` and `const scriptElement` to be `var scriptName` and `var scriptElement` is what is needed for the loadscript function (from what I can tell)

**Comment by JourneyOver** [comment]
oof I can't seem to test now as I'm now randomly getting this error for some reason >.<
![06-29-2022_22-23-32](https://user-images.githubusercontent.com/13910285/176586132-1e547648-fc49-4c96-b78f-5f0b6d05424b.png)

**Comment by JourneyOver** [comment]
@Ephenia Okay back to normal, from my latest testings everything is now working correctly from the looks of it, other than `catchfilterfantasia` is the only one missing.

**Comment by Ephenia** [comment]
Loving all this information and all the testing that you're doing, you're a huge help and I really appreciate it as well as your time! I must say that you're great with providing quality testing. You're always free to hit me up personally too if you want by the way, if it would also be easier or more convenient.

Anyway, are you happening to load all of the scripts by the way?

**Comment by JourneyOver** [comment]
> Loving all this information and all the testing that you're doing, you're a huge help and I really appreciate it as well as your time! I must say that you're great with providing quality testing.

@Ephenia it's not a problem at all, I try my best to test things and figure things out as I go along with issuing bug reports and such :p

> You're always free to hit me up personally too if you want by the way, if it would also be easier or more convenient.

Sounds good :D

> Anyway, are you happening to load all of the scripts by the way?

as for loading all the scripts, the only one that seems to be missing/not loading currently on multiple refreshes is the `infiniteseasonalevents` script. Everything else seems to be at least loading correctly now for the most part from my multiple refreshes from what I can tell.

**Comment by Ephenia** [comment]
Maybe the simpleweatherchanger could be bugging it out or interfering with it, since it also had the slight change to initialization. But, if that isn't it, then loading the script standalone would definitely tell if the script itself is the issue, probably.

**Comment by JourneyOver** [comment]
yea shit so confusing, because if I go to put `infiniteseasonalevents` script into the scripts folder to load it standalone, it then makes the `catchfilterfantasia` stop loading instead xD

**Comment by Ephenia** [comment]
You should be able to override all the scripts with blank ones with the same names and just have `infiniteseasonalevents` load, at least this should still be doable (I think) ;p

**Comment by JourneyOver** [comment]
okay so did a little bit of testing with everything blanked out in scripts and then moving between these last 3 (infiniteseasonalevents/simpleweatherchanger/catchfilterfantasia) these are the things I noticed:

With `infiniteseasonalevents` and `simpleweatherchanger` being the only two that wasn't blanked out, they loaded fine, if I re-added `catchfilterfantasia` it stopped loading the `infiniteseasonalevents` but `simpleweatherchanger` would still load, blanking out `simpleweatherchanger` didn't seem to bring back `infiniteseasonalevents` however if I was do that, if I was to blank out `catchfilterfantasia` again `infiniteseasonalevents` would however load just fine again.

so from this bit of testing it seems to be something to do with `catchfilterfantasia` causing issues atm.

**Comment by Ephenia** [comment]
Hm... quite interesting...

I wonder if it has something to do with the use of `window`, which may be unfortunate if that's actually the case.

**Comment by JourneyOver** [comment]
hmm yea that could possibly be it, sadly with how late it is getting here and the fact I sadly have to work in the morning I may need to call it a night on testing for now and come back to testing things again once I return from work tomorrow. I'll throw you an add on disc tomorrow once I'm around and we can see if we can figure things out.

**Comment by JourneyOver** [comment]
Sent you a FR on discord, and should be around for most of the day.

**Comment by JourneyOver** [comment]
Closing this since things since been fixed. :D
