### ISSUE TITLE
Desktop version stops working

### ISSUE THREAD

**Issue by michaellh221** [Ephenia/Pokeclicker-Scripts#164]
Not sure why but the desktop version just stops working, normal game goes on as usual but when scripts are added game crashes and not even the normal damage from the pokemons works. I think you were already working on it so this is gonna to be also for when the problem is solved, until you want to delete it.

**Comment by Ephenia** [comment]
Nothing much I can do with what information you're providing.

The client edit works fine for me with everything updated for me with everything updated on a fresh install (just tested today).

**Comment by michaellh221** [comment]
Ok so I just tested out it again and still not works for me. Made a full unistall of all files from game and added the mods.

What happens is the pokemons either on dungeons or at routes drop down to 0 but they don't "die" just stay at 0 hp. The DPS from the pokemons stops doing damage and only way to do damage is to do normal clicks. Also tried re-downloading the file for the desktop version runing with and without admin permissions.

**Comment by Zanes** [comment]
The same just happened to me. It started as I was fighting Cyntia at the last poke, any fights the pokemon will stay at 0 HP and nothing will happen.
I am using the same options as the one above, auto click at max but now it's bugged forever, even with autoclick stopped.

**Comment by JourneyOver** [comment]
Can any of you three send up your save file by chance? as I still yet have been able to reproduce this myself to even get an idea of what could be causing this for you three short of it just being something to do with your guys system environment.

**Comment by Drikanyx** [comment]
[[v0.9.7] PokeClickerSave_2022-07-06 00_24_07.txt](https://github.com/Ephenia/Pokeclicker-Scripts/files/9053063/v0.9.7.PokeClickerSave_2022-07-06.00_24_07.txt)
Sure thing, happened to back it up just before the clean install anyway.

**Comment by Ephenia** [comment]
Interesting, I see I get it while using your provided save, but do not get it on my own save and or unable to replicate it in any way on any of my test saves.

I'll look into it and provide a solution soon.

**Comment by Ephenia** [comment]
> [[v0.9.7] PokeClickerSave_2022-07-06 00_24_07.txt](https://github.com/Ephenia/Pokeclicker-Scripts/files/9053063/v0.9.7.PokeClickerSave_2022-07-06.00_24_07.txt) Sure thing, happened to back it up just before the clean install anyway.

The issue is in your specific case, is that you have Pachirisu in your Hatchery, even though you haven't actually caught it AKA it's not in your Pokédex.

That's why your game breaks.

**Comment by Ephenia** [comment]
So yeah, 1.2 will basically fix eggs bought from shops and things like fossils and whatever. That's what this issue basically relates to.

So, when you buy an egg from a shop and place it inside the hatchery, if it's of a Pokémon you don't have yet in your Pokédex, then Pokérus spreading to it wouldn't be possible. This isn't until you hatch it, it gets registered to your Pokédex as being caught, and then it goes back inside the Hatchery 👍
