### ISSUE TITLE
[INFO] Synthetic Shiny Synapse

### ISSUE THREAD

**Issue by Ephenia** [Ephenia/Pokeclicker-Scripts#166]
Back again for another banger of a script.

Something I surprisingly haven't been asked for or demanded much for (but that's what makes this release that much better and more fun for me to actually make).

You guys should know the drill, and it's time to walk you through what this script is about.

In the menu, you will see a new entry added (Shiny Modifier):
![image](https://user-images.githubusercontent.com/26987203/177792004-dcacaf18-22e1-425f-8af5-aea3b1b68832.png)

Clicking on it will bring up this brand-new modal:
![image](https://user-images.githubusercontent.com/26987203/178128650-d9376cf1-bb7e-4ecc-9d94-c2cec5fc4269.png)

Now, a lot of this should be self-explanatory just by looking at it.

On the far left, you got your categories. These are basically all the sources of where Pokémon are possible to be generated shiny (except for global, obviously).

To the right you will see input fields, these are for changing the shiny odds of whatever category that you would want to change specifically.

To the far right you have "modify" buttons, you press these after changing the odds to confirm them and for them to actually adjust.

The "✨Shiny Bonus" column calculates your shiny odds (based off your Shiny Charm's level). If your Shiny Charm happens to level up while this modal is open, re-open it if you want it to re-calculate.

This should also be the same thing with farm setups too, the shiny charm column should include calculating for this as well. You can treat the column as overall shiny bonus, basically.

At the top of the modal you have 2 buttons.

**Global Override** will make the shiny odds use the global odds for everything. This is great if you want everything to be the same, shiny odds (obviously).

**Reset Rates** will reset everything back to default rates and will make everything normal.

Also, if you're interested in disabling shinnies generating for something specifically, or entirely, you can set values to 0. Wasn't something intentional in the design of this, but I thought this was pretty cool in people maybe wanting to do no shiny challenges or incorporate that into their play.

**Comment by Mega-Rayquaza-8121** [comment]
yoooooo dats pog asf

**Comment by RedSparr0w** [comment]
> **Fun fact:** by default, only the Hatchery/Breeding doesn't actually use the Shiny Charm and other bonuses (yes, even the Wiki is and has been lying to us all). I have tested this and can confirm this myself, and it's why this bypass was added, specifically just for this.

As far as I am aware the shiny charm and farm bonuses definitely affect the shiny chance of eggs in the hatchery.
The bonuses only get applied when you gain steps throughout hatching, as otherwise you only need the charm active when you first put the eggs in.

With Shiny Charm (and 1x Starf):
![image](https://user-images.githubusercontent.com/7288322/178082833-748fafe8-18d4-4208-a5ab-1e6b20c5f1fa.png)

No Shiny Charm (and 1x Starf):
![image](https://user-images.githubusercontent.com/7288322/178082891-a695844f-6e68-48e7-990f-8396be06d360.png)

No bonuses:
![image](https://user-images.githubusercontent.com/7288322/178082982-c98625cd-5366-4337-9c3b-abfd4038228d.png)

There may be something else I am missing, but looking at the code it all seems to be fine.

**Comment by Ephenia** [comment]
Oh alright, now I see how it all is working.

I was a lot more focused on the `generateShiny` function, and figuring out what the `skipBonus` was all about. Now I see that the `skipBonus` is there as the calculation is done elsewhere for all this and after re-checking things with what you pointed out.

To be fair I was quite high most of the while as I was creating this with my brain half there, but still apologies for the unintentional misinformation due to my silly self, and I'll be correcting things on my behalf and updating things accordingly.

Also, quite surprised to see you here by the way, but thanks for the clarification^^
