### ISSUE TITLE
Auto clicker window no longer appearing

### ISSUE THREAD

**Issue by drizzt267** [Ephenia/Pokeclicker-Scripts#174]
So I went several days without refreshing my page.  Maybe a week.   When  the game recently got updated i refreshed the page and all was fine.   Today i refreshed the page because my browser had some update.

Now when i open the game in google chrome i cant see the window for the advanced auto clicker.   My other scripts seem to be working but the window for auto clicker is not appearing. for me to turn it on or off.

I have tried to reinstall the clicker as well as close and open the game several times but i still no luck.

**Comment by Ephenia** [comment]
Have you tried deleting it and re-installing through your script manager? Also, are there any errors in relation to it in the developer console?

**Comment by drizzt267** [comment]
have not looked in developer console i can look there for you now.

yes i did just  uninstall and reinstall and still no window.

while exploring other scripts and just letting game progress on a route i noticed that the Auto quest scrip is only starting half the quests and if i manually start on that it has not started it automaticaly quits the quest.

**Comment by drizzt267** [comment]
![image](https://user-images.githubusercontent.com/11465747/178859937-8c622a05-370d-403d-8eaa-88f82186eacf.png)
here is console when i refresh the page.

**Comment by Ephenia** [comment]
Try clearing `localStorage`.

In the console just type in `localStorage.clear()`, this should resolve the issue, hopefully anyway.

**Comment by drizzt267** [comment]
That worked thanks.    sadly lost 1 file because i had not backed it up recently but luckily have the main file still.

**Comment by Ephenia** [comment]
Oh right, I forgot to say to make sure you got your saved backed up beforehand and warning about that. My dearest apologies.

**Comment by drizzt267** [comment]
it is okay   it was not very far was still in first region

thansk for your help fixin the the issue.
