### ISSUE TITLE
app.asar for desktop with only Enhanced Auto Clicker

### ISSUE THREAD

**Issue by Oakwooooood** [Ephenia/Pokeclicker-Scripts#177]
Hello, the title pretty much says everything, I'm looking for a way to play on the desktop version with only the enhanced auto clicker script. I installed the app.asar you recommended but ended up with all the scripts installed and it works well but I would prefer a less cheaty way of playing.

Sorry for the request if it's already possible, I searched but couldn't find a way.
Thanks!

**Comment by Ephenia** [comment]
From the documentation:

> This script manages all other loaded scripts that succsessfully subscribe to it. All the scripts in this repository are automatically managed. This is mostly intended to be used in the desktop client as tampermonkey already allows to toggle scripts in a manner similar to this. Options are located in the Scripts tab in the settings<br>
![image](https://user-images.githubusercontent.com/26987203/179622307-ee003b80-03ce-426d-a285-0699a33db598.png)

It's included in the Script Manager (included in the edited app.asar).

**Comment by Oakwooooood** [comment]
Thank you! I didn't see that
Have a good day
