### ISSUE TITLE
Pokeball Filter assigning balls to all Pokemon

### ISSUE THREAD

**Issue by ZargoGames** [Ephenia/Pokeclicker-Scripts#179]
Whenever I assign a single Pokemon a set of Pokeballs using the filter, it assigns those balls to all Pokemon. It doesn't update the display until I search for a new Pokemon, but once I do it shows that all Pokemon are assigned to the balls that I only wanted a specific Pokemon to have.

**Comment by Ephenia** [comment]
Everything seems to work fine for me. Could you please provide some more information? Like how you're using the script, what browser you're using, Script Manager you're using, etc?

**Comment by ZargoGames** [comment]
I'm using Tampermonkey on Google Chrome. I reinstalled the script and it seems to be working properly now, I'm not sure what was causing the issue.

**Comment by Ephenia** [comment]
Interesting, I'm happy that it works now for you. Probably a minor issue somewhere or just a memory related issue or something.
