### ISSUE TITLE
Auto dungeon not working

### ISSUE THREAD

**Issue by drizzt267** [Ephenia/Pokeclicker-Scripts#181]
Auto dungeon glitches out and makes the dungeon map not load as you explore.    spams the cost of the dungeon but never clears it.
new as off last few days turned laptop on after 3 days..

can manually run the dungeons but if auto dungeon was on i have to wait for it to time out to see the map

**Comment by Ephenia** [comment]
Pick up v2.1 of `enhancedautoclicker` or reinstall the script via your Script Manager.

**Comment by drizzt267** [comment]
Actually after sleeping i thought of your last suggestion and i did Localstorage.clear and that fixed it. 

This time i remembered to save all 3 of my varies challenge files.

Do the scripts auto update when i am using them with tampermonkey?

**Comment by Ephenia** [comment]
They should auto update, but it will prompt you to update once an update it checked for (you'll have to manually approve of it).

Also, not sure why you'd need to be clearing `localStorage `again, weird. Could just be you and something on your end, but not really sure.
