### ISSUE TITLE
Custom Scripts to script manager

### ISSUE THREAD

**Issue by Dessastuff** [Ephenia/Pokeclicker-Scripts#183]
I looked at the example pictures, I'm willing to download whatever needed to edit it (I have notepad++) but I'm not sure where to put the code,  I am also hoping/assuming that basically I just need to substitute the ScriptName for the real one, and where it says initAutoQuests it would be initScriptName?

**Comment by Dessastuff** [comment]
I figured it out! :D thank you for your awesome scriptyness.

**Comment by Ephenia** [comment]
To anyone else wanting to know or would need an explanation for adding completely custom scripts to load, put the scripts in `root/resources/scripts` after you've loaded the game up once using the edited `app.asar`.

They'll boot and load as long as their names are anything different from anything in `root/resources`. However, if you want to override any of the repository scripts specifically, then you put your custom scripts under the same exact name in `root/resources/scripts`.
