### ISSUE TITLE
10k Protein achivement not working 

### ISSUE THREAD

**Issue by pedagova** [Ephenia/Pokeclicker-Scripts#185]
After buying 3k prots, the achivement is not updating the progress.
I had 9k before buying and 9k after.

![unknown](https://user-images.githubusercontent.com/19005373/181109674-4e2dc9fd-e8e0-45e2-9c57-d3efd1f5c6f9.png).

**Comment by Ephenia** [comment]
You should go to the official [Pokeclicker Github](https://github.com/pokeclicker/pokeclicker/issues) for this.
