### ISSUE TITLE
Dungeon bosses not affected by shiny modifier / karma mode

### ISSUE THREAD

**Issue by EugeneFabre** [Ephenia/Pokeclicker-Scripts#186]
I have been using karma mode and realized that dungeon bosses are not affected by it. No modifier seems to be updated when defeating a boss, and setting dungeon poké odds to 1 does not seem to affect dungeon bosses. Maybe they have their own category that would then need to be included in the modifiers?

**Comment by Ephenia** [comment]
Good catch, actually.

I didn't extensively test for this, but the next update, this will be accounted for.

It will be shared and included in with the same category for Dungeon Pokémon, as they both share the same constant for Dungeon Shiny rate.
