### ISSUE TITLE
Enhanced Auto Mine: Auto Sell Treasure shouldn't sell Shards

### ISSUE THREAD

**Issue by PTGigi** [Ephenia/Pokeclicker-Scripts#188]
**Bug report:**
If "Auto Sell Treasure" is turned ON, all Shards will be sold. Since Shards normally cannot be sold and have no Diamond value, they seem to simply be lost.

**Investigation:**
From what I understand, PokeClicker doesn't assign a valueType to Shards and underground items are defaulted to valueType "Diamond" ([UndergroundItem.ts](https://github.com/pokeclicker/pokeclicker/blob/develop/src/scripts/underground/UndergroundItem.ts)), which the enhanced auto mine script looks to use to determine whether to sell an item or not.

**Comment by 40Cakes** [comment]
I was wondering where tf all my shards were going 🤦

**Comment by Ephenia** [comment]
This will likely end up getting reworked anyway, since I did notice they actually implemented item locks and a sell all treasure feature recently. Nice to see, as this now means a auto sell treasure feature is just dead simple to do now on my behalf with re- implementing it.

**Comment by a1anne** [comment]
Hello, 
Just a small remark. I'm selling all my plate so it's not for me, but i think the fact that treasure and plates were appart was because we can't lock the plate. So for one who would like to keep it, for the daily deals or any other reasons, it might make a difference.

**Comment by Ephenia** [comment]
> Hello, Just a small remark. I'm selling all my plate so it's not for me, but i think the fact that treasure and plates were appart was because we can't lock the plate. So for one who would like to keep it, for the daily deals or any other reasons, it might make a difference.

You can lock plates:
![image](https://user-images.githubusercontent.com/26987203/182808170-37cd7bc1-aa1e-4da1-bb14-0f87f40683db.png)
