### ISSUE TITLE
AutoMulch causes the game to loop between requesting the game to mulch the land without stop.

### ISSUE THREAD

**Issue by Gelius3** [Ephenia/Pokeclicker-Scripts#189]
I just pressed "AutoMulch" to ON and it just kept doing that for ever.

**Comment by Ephenia** [comment]
```
autoMulchTimer = setInterval(function () {
    doMulch();
}, 1000); // Happens every 1 second
```
```
function doMulch() {
    FarmController.mulchAll();
}
```

I am getting much more of a laugh out of this than I probably should^

**Comment by Gelius3** [comment]
Tha meaning?
________________________________
De: Ephenia ***@***.***>
Enviado: 5 de agosto de 2022 09:16
Para: Ephenia/Pokeclicker-Scripts ***@***.***>
Cc: Gelius3 ***@***.***>; Author ***@***.***>
Assunto: Re: [Ephenia/Pokeclicker-Scripts] AutoMulch causes the game to loop between requesting the game to mulch the land without stop. (Issue #189)


autoMulchTimer = setInterval(function () {
    doMulch();
}, 1000); // Happens every 1 second


function doMulch() {
    FarmController.mulchAll();
}


I am getting much more of a laugh out of this than I probably should^

**Comment by Ephenia** [comment]
To give some context, it's because the script is one of the oldest scripts of the project and one of the first ones that I made, and when I first started this project I was winging a lot.

It's also why I laugh when people criticize the code, meanwhile I know the quality of the code within these scripts are nothing amazing. My newer scripts have been something nicer, but yeah, it's just funny to me, especially when I look at older scripts I haven't touched in ages here. This script being a prime example.

**Comment by Gelius3** [comment]
Ah i see. I assume that will be one of the changes whenever you update?
________________________________
De: Ephenia ***@***.***>
Enviado: 5 de agosto de 2022 23:50
Para: Ephenia/Pokeclicker-Scripts ***@***.***>
Cc: Gelius3 ***@***.***>; Author ***@***.***>
Assunto: Re: [Ephenia/Pokeclicker-Scripts] AutoMulch causes the game to loop between requesting the game to mulch the land without stop. (Issue #189)


To give some context, it's because the script is one of the oldest scripts of the project and one of the first ones that I made, and when I first started this project I was winging a lot.

It's also why I laugh when people criticize the code, meanwhile I know the quality of the code within these scripts are nothing amazing. My newer scripts have been something nicer, but yeah, it's just funny to me, especially when I look at older scripts I haven't touched in ages here. This script being a prime example.
