### ISSUE TITLE
Bug - Getting 3 DT after game update.

### ISSUE THREAD

**Issue by linkdest** [Ephenia/Pokeclicker-Scripts#193]
self explanatory title. I upgraded the new client to v0.9.10 and now I'm getting 3 dt in every route.

**Comment by Neozetare** [comment]
Seems to be a problem with the Catch Filter Fantasia script

**Comment by Ephenia** [comment]
The source modifications with functions being modified would need to be updated as I figure that's what it is. Will look into it soon.
