### ISSUE TITLE
[Feature Request] Enhanced Auto Clicker - Item mode

### ISSUE THREAD

**Issue by x-Axis-x** [Ephenia/Pokeclicker-Scripts#197]
Other than Farm Mode or Boss Rusher, I feel that there one more mode. It's sort of a hybrid of the two modes. 

It pick up all the chests then rush to the boss instead of fighting all the enemies.

**Comment by Ephenia** [comment]
Yeah, this has been suggested a bunch for a treasure mode, though I've also been annoyed and lazy with anything to do with working on Auto Dungeon features for quite a good while now.

https://github.com/Ephenia/Pokeclicker-Scripts/issues/22
https://github.com/Ephenia/Pokeclicker-Scripts/issues/75
https://github.com/Ephenia/Pokeclicker-Scripts/issues/140

I think you can see why. I typically don't ignore suggestions and would at least put tags or give some sort of response on them, but I suppose this also gives some reasoning/explanation to those wondering why. I definitely would read everything, but this is just how I can be personally with me appearing to just ignore things. You also would think the more people want something, the more inclined I would be to work on it, but that's not always going to be the case. This has been one of the most suggested things.

I do approve of the idea anyway, and it will eventually see implementation whether that's me or someone else who would want to help work on it, but yeah. If it's coming down to to me, I would just need to find the motivation for it, anyway.

**Comment by YoonKuen** [comment]
I see, before posting this I tried searching for similar request but only use label under enhancements. 

Thank you for explaining it, I totally understand where you're coming from. You should work on the things you want to work on.

**Comment by Tyrex512** [comment]
Hiroa's script on gitlab had an option to get all the chests and get to the boss in as little time as possible but it hasn't been updated since the dungeon floors update, I wonder if it's possible to adapt what he did?

**Comment by Ephenia** [comment]
> Hiroa's script on gitlab had an option to get all the chests and get to the boss in as little time as possible but it hasn't been updated since the dungeon floors update, I wonder if it's possible to adapt what he did?

It's possible, obviously.

However,  I think if you seen my earlier response, it's probably a better idea to help direct these people who actually make this stuff in the direction of the project and see if they'd like to PR or potentially even collaborate. Not only would it help give people and what is already this niche community more and help it grow, but they'll also actually get recognition for their work for this sort of stuff. Most people into the scripting side of the game follow this project and even check it daily.

I'm totally down for people working with me (especially more directly) and wish more people actually did. 

A lot more could actually get done.

**Comment by Tyrex512** [comment]
I agree, but I think the person who worked on those scripts isn't playing Pokeclicker anymore, and is likely playing other clicker/idle games ; at the very least our mutual acquaintance do (the script author is a friend of a Discord user with whom I happen to share a server, but not talk often as it's a pretty big server)
