### ISSUE TITLE
Catch filter doesn't support Beast Balls yet

### ISSUE THREAD

**Issue by umbralOptimatum** [Ephenia/Pokeclicker-Scripts#201]
As the title says. Mostly relevant during the UB questline to filter for whichever species still needs to be caught. Those Beast Balls are expensive and dang Blacephalons keep wasting mine >:(

**Comment by Ephenia** [comment]
Me being completely oblivious to Alola's actual release
![image](https://user-images.githubusercontent.com/26987203/183313625-73ea5d4d-956b-48e6-8b61-ae5b27145cbd.png)
