### ISSUE TITLE
[BUG] Catch Filter Fantasia Broken on update v0.9.12

### ISSUE THREAD

**Issue by mattewar** [Ephenia/Pokeclicker-Scripts#207]
I have the folowing setup on tampermonkey
![image](https://user-images.githubusercontent.com/12835252/185383850-139bfee1-3d59-45bc-a7e5-e9a8ff376cfe.png)
I had the catch filter fantasia active but then it would result on the folowing console errors and stop all the other helpers from working
![image](https://user-images.githubusercontent.com/12835252/185384048-6eb29f74-28ef-4b24-a550-86c2d1d6840b.png)
By disabling the catch filter everything else worked fine.

**Comment by Ephenia** [comment]
I derped with something.

I'll be rolling out a fix shortly.

**Comment by Ephenia** [comment]
Something to note as well, the Reset Balls button is broken and will bug things, you will have to refresh the game if you use this feature.

I looked briefly into this and couldn't figure out why it's broken, but will have to look further into it later.
