### ISSUE TITLE
[BUG] Autoclicker not working on Safari

### ISSUE THREAD

**Issue by Rock-bell** [Ephenia/Pokeclicker-Scripts#208]
Seems like auto clicker is not working on safari. no clicker and no grahical interface on Safari.
I have tested version 2.2 and 2.3
I have tested an other script (Auto-mine) and it worked fine.

On the same computer, the Auto clicker script works fine on Firefox.

**Comment by Ephenia** [comment]
If it's not Chromium based of a browser, then it's not officially supported or there's likely going to be issues with these scripts somewhere.

For something like Safari I wouldn't bother going out of my way to do support for (as this is also MacOS which I personally don't care for) unlike something like Firefox. However, if someone wants to do fixes and provide support for it, then I'm open to it.
