### ISSUE TITLE
Auto Hatchery not working while every other script good

### ISSUE THREAD

**Issue by Kiyarazzz** [Ephenia/Pokeclicker-Scripts#209]
I am using Chrome on mac. Every script (I have 16 scripts running in total) works except autohatchery. The issue started recently after I updated the scripts in tampermonkey.  I tried reloading the page multiple times, deleting and adding in tampermonkey. 
The issue actually sort of existed before, about two months ago, when I noticed that two duplicate buttons existed on the hatchery bar. It happened sometime after I updated the autohatchery script, but as it had no impact on actual gameplay, I ignored it. 

Sorry for this seemingly dumb issue. I went through existing issues and could not find an answer.

**Comment by Ephenia** [comment]
https://github.com/Ephenia/Pokeclicker-Scripts/issues/174

Could try what I said there with clearing `localStorage`, other than that and if it doesn't work, then I wouldn't know. Would need to see the developer console for possible errors.

**Comment by Kiyarazzz** [comment]
Thanks it worked! And thanks so much for the wonderful scripts:)
