### ISSUE TITLE
[Feature Request] Auto Hatchery Filter

### ISSUE THREAD

**Issue by carti1k** [Ephenia/Pokeclicker-Scripts#21]
It would be cool to have the Auto Hatchery only be able to hatch certain pokemon you want from a filter such as your "Favourite" pokemon or like "Fire Type" and if all of those pokemon have been hatched/are being hatched it will wait until those pokemon hit level 100 and appear in the filter again rather than auto adding pokemon into the hatchery

**Comment by Ephenia** [comment]
This is now implemented as of version 1.5 (commit 939c88b65be46f499e45cc4e1eb9f7637b28f097).

Some things to note about this new feature:

- When setting the category to "Favorite", only your Favorited Pokémon will be placed inside the Hatchery, like so:

![image](https://user-images.githubusercontent.com/26987203/151720031-08cf4f60-8eb0-4ee7-8bd4-6dbdda1b4e89.png)

- When there are no Favorited Pokémon available to be placed inside the Hatchery, nothing will be placed inside (normally random Pokémon are placed inside instead when nothing left is available to be placed inside via specific filtering)
- It's now possible to Favorite Pokémon even when the Hatchery/Hatchery Queue is full, like so:

![image](https://user-images.githubusercontent.com/26987203/151720239-58b313b1-73f8-4c76-8642-eb261b6303eb.png)
**This was not possible to do so before.**

- Using the Favorite category will work in combination with other filters (ex. you can put your favorite Fire type Pokémon that aren't Shiny yet inside the Hatchery only)
<hr>

Hopefully I understood and executed this idea well, and I hope that it's a nice and welcome feature to all. If there are any issues with this or any feedback to further improve this any, feel free to open a new issue anytime.

**Comment by carti1k** [comment]
It's perfect! Thank you so much for adding this <3
