### ISSUE TITLE
[BUG] Can't choose quests type

### ISSUE THREAD

**Issue by Tyrex512** [Ephenia/Pokeclicker-Scripts#219]
Hi,

When I turn on the option to automatically start and claim quests, there are some quests that aren't automatically added. I know there's an option to accept or remove specific type of quests, but the thing is, when I click on the type of quest that isn't added, like "Gain 3852 farm points", it either removes a quest I already have (like "Hatch 31 eggs") or add another unadded quest (like "Harvest 46 Leppa Berries").

I think a good fix would be to either have a button to accept all type of quests, or an option to manually choose which quest types you accept or "ban".

**Comment by RuyoTramp** [comment]
yeah it has been bugged for a while now

**Comment by Ephenia** [comment]
Should be fixed now as of 2009aed36e8a2305306d82e36144916b92c575d3.
