### ISSUE TITLE
Hatchery will not spread Pokerus at all whilst "Perky Pokerus Pandemic" is active

### ISSUE THREAD

**Issue by Xross98** [Ephenia/Pokeclicker-Scripts#221]
I have done ScriptFixerUpper, in case you were going to ask that. :p

Deactivating the PPP script was enough to make Pokerus start spreading, I assume it has something to do with the base game allowing Pokerus to spread without the starter, which is all PPP did in the first place. Probably better off removing it altogether since it's unnecessary now.

**Comment by Ephenia** [comment]
The script is not getting removed. Its necessity is also subjective on a per user basis even in its current state.

It will eventually get updated when I have time or am motivated enough to do so.
