### ISSUE TITLE
Enhanced Auto Mine version got changed from 1.7 to 1.1

### ISSUE THREAD

**Issue by iamc24** [Ephenia/Pokeclicker-Scripts#229]
It's just a small issue with the recently updated userscript headers; I presume it was a mistake, since the pull request said it didn't change version numbers. I noticed it when I reinstalled all the scripts, it said downgrade instead of reinstall like every other script did. I just figured I should let you know since no one else seemed to have noticed it yet.

**Comment by Ephenia** [comment]
Thank you for letting me know.
