### ISSUE TITLE
[question] How can i change the enemy/s display to have 2 decimal places?

### ISSUE THREAD

**Issue by RuyoTramp** [Ephenia/Pokeclicker-Scripts#23]

**Comment by Ephenia** [comment]
Change this @ line 206:
`enemySpeed = ((App.game.party.calculateClickAttack() * 20) / enemyHealth).toFixed(1);`

To this:
``enemySpeed = ((App.game.party.calculateClickAttack() * 20) / enemyHealth).toFixed(2);``

**Comment by RuyoTramp** [comment]
Thank you very much
