### ISSUE TITLE
Hatchery is not picking the right pokemon

### ISSUE THREAD

**Issue by PaytonLunde** [Ephenia/Pokeclicker-Scripts#231]
the newest update just broke the way the script picked the pokemon, and can't figure out how its picking them to fix it. It is ignoring the pokemon list sorting and appears to be completely random.

**Comment by Ephenia** [comment]
`filteredEggList` needs to be reworked/looked into.

I am briefly looking into it now to see if I can sort it out.

**Comment by Ephenia** [comment]
The main issue was `BreedingFilters.region.value()` being changed since the update and is set to a default value of `127` causing `filteredEggList` to return an empty array.

I've rolled out an update to adjust to the new update and the Hatchery should be functional again, but not fully tested. 

I'll leave this open in the meantime.

**Comment by PaytonLunde** [comment]
Does not seem to be working still

**Comment by Ephenia** [comment]
> Does not seem to be working still

Through some basic testing it appears functional and just like it was before the update, filters are working as well as in combination with one another. I don't notice anything broken or not functional as intended.

**Comment by CptGryps** [comment]
Hello!
It is not working for me either. The only filter I use is Shiny Status (Not Shiny), and sorted by Breeding Efficiency, but the Pokemon still get randomly picked.
I have tried updating the script manually, deleting/reinstalling it, refreshing the page, etc. but it didn't change anything.

Is there something else I should try?

**Comment by set44599** [comment]
You should try re-selecting _every_ filter present in the hatchery menu, such as Region, Type, etc. Filters break easily in this game, and there's a number of vanilla bugs that could be causing this.

**Comment by CptGryps** [comment]
I followed your suggestion and tried re-selecting every filter.

It didn't work, however I have found that the script works fine with every region except "Galar" and "All". If I select either of those two, the Pokemon get randomly picked again.

**Comment by TheDumbSeal** [comment]
Can confirm above, filters only work when doing that

**Comment by Ephenia** [comment]
> I followed your suggestion and tried re-selecting every filter.
> 
> It didn't work, however I have found that the script works fine with every region except "Galar" and "All". If I select either of those two, the Pokemon get randomly picked again.

![image](https://user-images.githubusercontent.com/26987203/197386125-82fb3242-ddd1-4e4b-aa10-7e3aab590c4d.png)

Galar does not exist.

**Comment by CptGryps** [comment]
![image](https://user-images.githubusercontent.com/116481639/197386404-1bc0a0f6-d6e8-44a2-a661-7760eea2f10d.png)

It exists for me?

**Comment by Ephenia** [comment]
Now I see what the issue is Only the highest region you've unlocked will show in the filter (only up to Alola shows as I have not unlocked Galar yet on my save).

I'll roll out another update in a bit to account for this.

**Comment by Ephenia** [comment]
Updated again.

The Region filtering should be fine now and shouldn't break anything.

**Comment by CptGryps** [comment]
Oh, I see! Yes it makes sense.
I have tried it and it seems to work for me again.

Thank you very much for your work and the fast update! :)

**Comment by Ptitecocotte** [comment]
Hello,
 
The auto hatchery doesn' work anymore for me.
The "on/off" button is not here. It's look like the script is not enable (but it is). But auto cliker and auto mine are ok...

Thanks to help me about this issue :)

**Comment by Ephenia** [comment]
> Hello,
> 
> The auto hatchery doesn' work anymore for me. The "on/off" button is not here. It's look like the script is not enable (but it is). But auto cliker and auto mine are ok...
> 
> Thanks to help me about this issue :)

[Try this.](https://github.com/Ephenia/Pokeclicker-Scripts/issues/214)

**Comment by Ptitecocotte** [comment]
> > Hello,
> > The auto hatchery doesn' work anymore for me. The "on/off" button is not here. It's look like the script is not enable (but it is). But auto cliker and auto mine are ok...
> > Thanks to help me about this issue :)
> 
> [Try this.](https://github.com/Ephenia/Pokeclicker-Scripts/issues/214)

Already try this this morning before to post here. It didn't change anything :/

**Comment by Ephenia** [comment]
> > > Hello,
> > > The auto hatchery doesn' work anymore for me. The "on/off" button is not here. It's look like the script is not enable (but it is). But auto cliker and auto mine are ok...
> > > Thanks to help me about this issue :)
> > 
> > 
> > [Try this.](https://github.com/Ephenia/Pokeclicker-Scripts/issues/214)
> 
> Already try this this morning before to post here. It didn't change anything :/

Could you try seeing if there are errors in the console (F12) when you load into your save?

**Comment by Ptitecocotte** [comment]
There were a lot. I clean up my browser and all is ok now ! :)
Thank you so much !

**Comment by Dionisos94** [comment]
If people have the same issue than Ptitecocotte (I did) of not seeing the Auto Hatch button, here is what I did to fix it:
1. Save your game to avoid losing data
2. Press F12 and click on Storage, go to "Local Storage" and right-click on it to press "Delete All"
![image](https://user-images.githubusercontent.com/15048957/198022758-fea37492-e6e7-4e7d-8936-47198bb03fa7.png)
3. Reload the game and load your save

That will remove old data stored in your browser that do not seem compatible with the new script.

Issue was coming from this line where the Json was not parsable.
![image](https://user-images.githubusercontent.com/15048957/198022370-52140a06-cb56-4356-9a8d-0bac9bfcc916.png)

**Comment by Tyrex512** [comment]
Looks like there's still some issues with secondary filters (such as Pokerus status), I was trying to give every Pokemon the Pokerus so I filtered for uninfected Pokemon, and it put a Pokemon already infected multiple times (namely Magikarp and Gyarados, since I was sorting by egg steps to go through the list faster)

**Comment by Ephenia** [comment]
> Looks like there's still some issues with secondary filters (such as Pokerus status), I was trying to give every Pokemon the Pokerus so I filtered for uninfected Pokemon, and it put a Pokemon already infected multiple times (namely Magikarp and Gyarados, since I was sorting by egg steps to go through the list faster)

Because I haven't touched the Pokerus filter yet, and it's not included in the script or checked yet as it's a newer filter that was introduced to the game.

It will be done eventually, whenever I choose to stop ignoring it like I have been.
