### ISSUE TITLE
AutoGYM isn't working properly in Galar

### ISSUE THREAD

**Issue by K0STYURIK** [Ephenia/Pokeclicker-Scripts#232]
Galar league only have 4 people instead of five, so choosing options "5" and "ALL" results in battling only Leon (4)

Both Stow-on-Side and Circhester have two GYMs, but enabling any option of AutoGYM (1, 2, 3, 4. 5 or ALL) results in nothing. There are currently no way of automatically battle Bea, Allister, Melony or Gordie

**Comment by kevingrillet** [comment]
The problem come from here I think: 
https://github.com/Ephenia/Pokeclicker-Scripts/blob/c1e363f14d920d5343be1769470476001b6af4c6/enhancedautoclicker.user.js#L305-L311

Circhester:
![image](https://user-images.githubusercontent.com/7203617/197570423-2ca5d42a-63db-4d63-9e7e-813bba2cf817.png)

Stow-on-Side:
![image](https://user-images.githubusercontent.com/7203617/197569923-a0d228db-1232-4930-a40c-4ea9253f809b.png)

WyndonStadium:
![image](https://user-images.githubusercontent.com/7203617/197569813-0696a864-3c68-4ddc-b9ec-07a778bc3521.png)


Maybe something like that?

```js
champCheck = player.town().content.filter((c) => ['Champion', 'Gym'].includes(c.constructor.name)).length > 1
```

**Comment by K0STYURIK** [comment]
I'm totally dumb in terms of JavaScript, so I don't know how to test it, if it isn't implemented in .JS file

However, today I found similar problems in "Master Dojo Battle Court" (where there are four people in total and choosing AutoGYM options [5] and [ALL] resulting in battling only Mustard) and Freezington, where Peony doesn't count as a GYM and turning AutoGYM on doesn't work for him regardless of chosen number [1] or [ALL]

**Comment by Ephenia** [comment]
Pretty swift rewrite.

So, Auto Gym functions a bit differently now.

Using "ALL" no longer works based off the schema of what is essentially an Elite Four (meaning 4 Gyms then a Champion).

Also, "ALL" no longer requires you to have the Champion unlocked for it to function.

Using "ALL" should loop through Towns that even have 2 Gyms now (Stow-on-Side as an example). In such an instance Auto Gym will basically keep fighting them back to back. 

The rest still essentially works the same as before, but I still rewrote it. So, it's of course, not fully tested.

**Comment by Ashyaa** [comment]
The initial problem seems to have been fixed, as options 1, 2, 3 and ALL work properly in most cases, but I think there is a side effect on Wyndon Stadium in Galar. As it stands, automating the Leon fight does not work with option '4'. Choosing option '5' is similar, but at least expected. In both cases, the following exception is uncaught: 
![image](https://user-images.githubusercontent.com/7237493/199071963-a5dd07b2-c6b2-4d0e-bbfe-06df7e3a79a1.png)

Tested on Desktop and Browser.
