### ISSUE TITLE
[Feature Request] Add the option for a timer to trigger a quest refresh to the Auto Quest Script

### ISSUE THREAD

**Issue by Kazard** [Ephenia/Pokeclicker-Scripts#235]
Hopefully somewhat straight forward, I'd like the ability to set a timer that triggers quests to be refreshed. This would allow more automation of quests as currently I have to keep an eye on them and refresh them when the easily completed ones are finished. Most of the quests complete after one or 2 minutes, so maybe the option to choose between a minute amount ranging from 1 to 10 would do the trick. 
If you want to go a bit above and beyond maybe the timer doesn't start until one quest is finished? 
This would make finishing the 5000 quest achievement much easier, so I appreciate the consideration!

**Comment by snab43** [comment]
+1 on this

Was about to open an issue to ask for the same thing. I actually manually got the 5000 quest achievement over time, but still for accumulating quest points, that would be helpful.

At the very least, a one click button to refresh vs the 3 clicks it takes in vanilla.
