### ISSUE TITLE
[Feature Request] Manually Change Weather

### ISSUE THREAD

**Issue by Dubz9** [Ephenia/Pokeclicker-Scripts#24]
Clicking on the icon shows a popup with the different weather types wich will change to that weather when selected and confirmed.

**Comment by Ephenia** [comment]
I will consider the idea and look more into it sometime. If I come up with something then I may make a script for it.

**Comment by Ephenia** [comment]
This is now a script as of commit 6462f49d1e2b3973a222e0034c0c0d23a0522e6a. Special thanks to KarmaAlex for creating this! ♥
