### ISSUE TITLE
[Bug][Catch Filter Fantasia] Route not being recognised as such

### ISSUE THREAD

**Issue by Ignorance001** [Ephenia/Pokeclicker-Scripts#242]
Hello,

I found a bug in the Catch Filter Fantasia script with the "Load Route" button and did not find any issue about it. On specific route, it replies the error message "You are not on a route."
From what I notice, I would say it only happens when the pokemons available on the route depend on parameters (weather, quest).

To be detailed in the routes where it's happening:
- Hoenn, Route 119 where there are some weather dependant pokemons;
- Alola (Ula'ula Island), Haina Desert and Route 17 where there are some Ultra Beast Hunt quest dependant pokemons;
- Alola (Poni Island), Poni Grove where there are some Ultra Beast Hunt quest dependant pokemons;
- Galar (South Galar), Rolling Fields, Dappled Grove, West Lake Axewell, East Lake Axewell, Axew's Eye, Watchtower Ruins, Giant's Seat, South Lake Miloch, North Lake Miloch, Motostoke Riverbank, Bridge Field, Stony Wilderness, Giant's Mirror, Giant's Cap, Lake of Outrage and Hammerlocke Hills where it appears some pokemons are weather dependant;
- Galar (North Galar) Circhester Bay, Route 9 and Route 10 where it appears some pokemons are weather dependant;
- Galar (Isle of Armor), all routes where it appears some pokemons are weather dependant;
- Galar (Crown Tundra), all routes where it appears some pokemons are weather dependant.

Also, on an other point, the roaming pokemons are not detected in the filter when we load a route where they are. It is minor compared to the bug explained above but since I am already opening an issue...

Anyway thank you for the script that already saved me a lot of time.

**Comment by Macharius92** [comment]
My PR only tries to solve the "You are not on a route" issue.

Not sure how to list roaming pokemons for now (but i'll try to find)

**Comment by palex00** [comment]
Bump. This issue still persists.

**Comment by Ignorance001** [comment]
With the PR being merged, this seems to be solved.
Thanks!
