### ISSUE TITLE
[Bug][Additional Visual Settings]Options not working anymore

### ISSUE THREAD

**Issue by Ignorance001** [Ephenia/Pokeclicker-Scripts#243]
Hello,

Since the Galar update of the game it appears some addition visual settings are not working anymore.
These settings are:
- Show wild Pokemon Name;
- Show wild Pokemon Image;
- Show Pokemon Health;
- Show Catch Icon.

Pokemon Name, Pokemon Image and Pokemon Health are showing independantly of the options being checked or not.
Catch Icon sometimes still appears even though the option is unchecked.

**Comment by BadFlo** [comment]
Same issue on my side.
I tried to use the Fixer Upper, to no avail.

**Comment by Ephenia** [comment]
Yeah, because the UI changed, so the settings need to be updated.

**Comment by Ignorance001** [comment]
Thank you for the fix.
