### ISSUE TITLE
Enhanced Auto Hatchery doesn't work anymore with version 0.10.2

### ISSUE THREAD

**Issue by ValentinUsedREKTItsSuperEffective** [Ephenia/Pokeclicker-Scripts#251]
Line 298: ` const starterName = GameConstants.Starter[player.starter()];`

This give the following error : 
TypeError: player.starter is not a function

**Comment by ValentinUsedREKTItsSuperEffective** [comment]
Changing `player.starter()` by `player.regionStarters[GameConstants.Region.kanto]()` fix the bug

**Comment by Ephenia** [comment]
The typical report an issue and providing a fix without a PR.

**Comment by BadFlo** [comment]
> The typical report an issue and providing a fix without a PR.

Do you want me to create it for you?

**Comment by darkshurikens** [comment]
not sure why but it did in fact fix the whole not working issue

**Comment by Herbvek** [comment]
Thanks a lot Valentin, it did work.

**Comment by adastras3** [comment]
> Changing `player.starter()` by `player.regionStarters[GameConstants.Region.kanto]()` fix the bug

Sorry to sound dense but where do I put this code? In the auto hatchery script?

**Comment by axlmcc** [comment]
`GameConstants.Starter[player.regionStarters[GameConstants.Region.kanto]()];` will just return one of `'Fire', 'Water', 'Grass'` rather than the name of the chosen starter Pokemon. StarterPKMN ends up being undefined when we pass it to `App.game.breeding.addPokemonToHatchery()` on line 296.

Added a quick change to use the starter ID in the definition of starterPKMN. If there's an easier way to grab the starter name that I'm just not aware of, please let me know!

**Comment by jordanmacker** [comment]
Hi, I have an issue with autohatch, it doesn't add any pokemon into the hatchery (even with sync on and my list is full I can add them by cliking). It automatically hatches eggs, or fossils but never pokemon I have no idea why ? 
Anything I can do for this issue ? 
Already had it with an older version but it gets resolved by itself and now it's back.
Thanks

**Comment by adastras3** [comment]
>issue with autohatch
Yea - I see the two potential fixes here and I have tried both in my .js file but neither work for me. I am using the desktop version so maybe that is why?

**Comment by jordanmacker** [comment]
> > issue with autohatch
> 
> Yea - I see the two potential fixes here and I have tried both in my .js file but neither work for me. I am using the desktop version so maybe that is why?

Got exactly the same issue with Desktop version (only have issues with hatchery), no idea why but browser or desktop exactly same behavior...

**Comment by adastras3** [comment]
> Thanks, but replacing player.starter() by player.regionStartersGameConstants.Region.kanto fixed the bug ^^

How do you do that? I notice when I replace `player.starter()` in the .js, and launch the game, `player.regionStarters[GameConstants.Region.kanto]()` gets changed back to `player.start()`

**Comment by jordanmacker** [comment]
I modified it on my script in tampermonkey and now it's fine on the browser, didn't tried desktop version
