### ISSUE TITLE
Infinite Protein Use

### ISSUE THREAD

**Issue by Iamthebestintheworld222** [Ephenia/Pokeclicker-Scripts#26]
The 30 protein limit is getting kind of boring so I was maybe hoping if you could make a script to have infinite proteins to use for Pokemon.

**Comment by Ephenia** [comment]
Great idea! I know it's something I eventually had wanted to take a look at. I approve of the idea and it can surely be made possible. Look forward to seeing this soon.

**Comment by Ephenia** [comment]
This is now a new feature and made possible via the creation of the script "Omega Protein Gains" (commit 2bf7f0967e41d9a2949e50faf454beeb3000c099).
