### ISSUE TITLE
[Bug] No script working properly on desktop client after last update

### ISSUE THREAD

**Issue by Ignorance001** [Ephenia/Pokeclicker-Scripts#261]
Hello

With the lastest update I encoutered today, no script seems to work properly anymore on the desktop client (which I also updated).

Does anyone have tested the scripts on the browser version of the game?

As an example, the simple auto farmer script prevents the clock on the berries, meaning they cannot grow.
Also the enhanced auto clicker script doesn't work and prevents the pokemon attack.
Etc.

**Comment by Ephenia** [comment]
Weird. Everything still works fine for me after updating.

Anyone else having issues?

**Comment by Ignorance001** [comment]
So I tested on the browser and after using the script fixer upper, no issue remains.

Regarding the desktop client: the catch speed adjuster, enhanced auto mine, simple auto farmer, enhanced auto clicker, enhanced auto hatchery, infinite seasonal events, simple weather changer scripts don't appear even though they're checked in the settings list.
I tried to only leave the script fixer upper but it didn't change anything as I didn't get any message nor reload from it as on browser.

I'll stick to browser for now I guess.

**Comment by Ephenia** [comment]
> Regarding the desktop client: the catch speed adjuster, enhanced auto mine, simple auto farmer, enhanced auto clicker, enhanced auto hatchery, infinite seasonal events, simple weather changer scripts don't appear even though they're checked in the settings list. I tried to only leave the script fixer upper but it didn't change anything as I didn't get any message nor reload from it as on browser.

There's a script that's broken on your end that's likely causing this issue.

If a broken script is loaded while others are enabled, then it will end up breaking all the others (causing them to fail to load).

You could try and find the script by playing around with loading different ones, or the console may be of help possibly with finding it.

Also, the `scriptfixerupper` doesn't do anything (currently) on the Desktop version.

**Comment by TirOFlanc** [comment]
Hello

For me too, the scripts were not working anymore.

I made a backup and I uninstalled everything, cleaned it up and reinstalled it.

Now it works again.

One problem remains, I don't have the "Scripts" tab !

![image](https://user-images.githubusercontent.com/56934692/210141028-cc410ab5-2067-4162-95b0-9a95d0d84aa7.png)

**Comment by Ignorance001** [comment]
I uninstalled and cleared the files (if I found all of them) before reinstalling the client. The issues only come when I replaced the app.asar file which is loading the scripts.
Once the file is replaced, the client even becomes borderless which is very strange.
The issues are still present whether or not I check the scripts in the settings and I can't remove them since they'll be downloaded automatically if they're missing.
As for the console, I have no clue how to, sorry.

**Comment by ZeroX159** [comment]
From what I found, it seems to be the catch filter that is breaking the game for the desktop version. When enabled it causes time to 'freeze' in game.

**Comment by TirOFlanc** [comment]
To clean up, I used "everything" to search for "pokeclicker" and easily find all the folders concerned.

You know if you deleted everything if when you launch the game after reinstalling it, the program downloads the game data and you don't have your game loaded (remember to make your backup before deleting everything!).

![Caseryhzbvjicrtjzvyjvzsrjvzsryjvsryjsyjjefe](https://user-images.githubusercontent.com/56934692/210153032-f67da895-2a82-4c94-8017-a47a1da01799.PNG)

You have "pokeclicker-desktop" in "roaming", "pokeclicker-desktop-updater" in "local" and obviously the folder where you install the game.

**Comment by sdkyron** [comment]
I'm having issues aswell, for example, i can't disable quests anymore, if i click quit, it reappears instantly. Also, the options to disable name, image etc, don't work at all, only hide healthbar works. (browser)

**Comment by Ephenia** [comment]
Well let's see.

Does downloading and using v1.2.0 and using the new `app.asar` solve everything for you guys?

Refer to [this also](https://github.com/Ephenia/Pokeclicker-Scripts/issues/263#issuecomment-1370122740).

**Comment by Ignorance001** [comment]
It does solve everything!
Thanks!
