### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by NicoTine34** [Ephenia/Pokeclicker-Scripts#263]
New Discord Rich Presence not working on desktop version (stay as default) and dont have the top bar app to reduce and close window.
No scripts tab in settings too.
Im using the new Desktop version 1.2.0

**Comment by Ephenia** [comment]
Just don't use v1.20 for now?

Starting from v1.1.0 works fine, the only thing that's broken with it is the Discord RCP that I know of.

**Comment by NicoTine34** [comment]
yep i revert back for the moment Hope you can update it for the new client ❤️

**Comment by Ephenia** [comment]
I can take a look into updating it,

I figure things with the `app.asar` changed, and whatever got changed needs to be updated into the edited one.

**Comment by Ephenia** [comment]
New `app.asar` is out for [v1.2.0](https://github.com/RedSparr0w/Pokeclicker-desktop/releases/tag/v1.2.0).

I haven't really tested it out much, but it should be all good.

Coming with this update as well, I added some QoL

Now, upon launch, there should be a `settings.ini` file that gets created in the directory of the `Pokeclicker.exe`.

This file allows you to adjust the client size (in pixels) and lets you set the client to be maximized or not.

Resizing the client will also automatically adjust the `ini` file and save the size of the client accordingly. This way, when you close and re-open the client the next time, it should be how you left it.

I was going to do exact and precise positioning, but this should still be good enough for now.

If there are any issues with this new update, just let me know here.

**Comment by NicoTine34** [comment]
Everything seems to work perfectly, thank you so much for the quick update !
