### ISSUE TITLE
[Bug] auto hatchery not properly working with categories

### ISSUE THREAD

**Issue by Honveruhth** [Ephenia/Pokeclicker-Scripts#264]
Hi,

ive noticed that when using the auto hatchery script and applying a category filter, it igrones the sort settings that where set, like times hatched, base attack etc. Instead it seems to default to pokemon# ascending. Im not really sure why its happening since the sort settings do take effect when not using the category filter.
I also tried the sciptfixerupper but that didnt help. im not sure what causing it and also if its relevant im using the client version.

edit: it seems i might have made an error. the settings wihtin the daycare menu dont influence the selected pokemon at all, i needed to adjust the setting on the pokemon list to get the desired effect. but that also means that the option 'pokemon list sync' is either not working or i misunderstood what it meant

**Comment by morsok** [comment]
I'm having the same issue, I've set up filters to only train Pokemon that are not yet mega-evolved but it seems to follow the Pokemon list on the general screen and not the hatchery screen.

**Comment by Ephenia** [comment]
`Pokémon List Sync` makes the hatchery work in sync with work with the Pokémon List (in the general game screen).

You need to have this off for categories and other filters inside of the Daycare to work as you would expect it to.

This is how I coded it anyway, and the intent of the `Pokémon List Sync` feature being there. Whether it still works or not how I intended it to, I have no idea.

**Comment by morsok** [comment]
Ah, it was a bit misleading for me then, but there must be a bug because even when putting it to OFF, it doesn't follow the order of Pokemon on the hatchery list screen with all the filters.

**Comment by vityav** [comment]
I think there's one bug (or probably just outdated bit) and one bit of confusion. The confusion is that the hatchery main sorting criteria (base attack, breeding efficiency, etc) uses what's set on the party list from the main screen, not what's set on the hatchery screen. If you sync them it's less confusing, but requires a button not accessible on a phone screen (or not on mine, anyway. Some CSS attribute gets set and hides it on smaller screens). You could also just edit the code on yours to force syncing on.

The other part is that this doesn't filter on mega status. You can throw this in the filteredEggList filter with the others and it should work (I can confirm the first filter works. Haven't mega evolved anything yet to test the others):

```
                const uniqueTransformation = BreedingFilters.uniqueTransformation.value();
                // Only Base Pokémon with Mega available
                if (uniqueTransformation == 'mega-available' && !PokemonHelper.hasMegaEvolution(partyPokemon.name)) {
                    return false;
                }
                // Only Base Pokémon without Mega Evolution
                if (uniqueTransformation == 'mega-unobtained' && !(PokemonHelper.hasMegaEvolution(partyPokemon.name) && partyPokemon.evolutions?.some((e) => !App.game.party.alreadyCaughtPokemonByName(e.evolvedPokemon)))) {
                    return false;
                }
                // Only Mega Pokémon
                if (uniqueTransformation == 'mega-evolution' && !(PokemonHelper.getPokemonPrevolution(partyPokemon.name)?.some((e) => PokemonHelper.hasMegaEvolution(e.basePokemon)))) {
                    return false;
                }
```

I'm hesitant to submit an untested PR, but let me know if it seems worthwhile and I can put that together.

**Comment by morsok** [comment]
@vityav Hey if you throw a PR I'll test it to make sure it works. I'd really love for the hatchery when the pokemon list sync is not ON to use the same list as the hatchery screens, so it uses the same filters.

**Comment by vityav** [comment]
@morsok The PR is up at https://github.com/Ephenia/Pokeclicker-Scripts/pull/311 if you want to give it a test. I've been running it for a couple days on both PC and Android and haven't encountered any bugs, but I've only just reached my first mega evolutions so haven't had a lot of time for edge cases to pop up. I can at least confirm it works even before the dropdown is there for mega evolutions though, and that the sorting uses the hatchery sort dropdown for as long as I've been testing it.
