### ISSUE TITLE
[Feature Request] Shortcut for Region change

### ISSUE THREAD

**Issue by SpiderlingJr** [Ephenia/Pokeclicker-Scripts#265]
Hi all,

sorry if this turns out to be a duplicate, but I just couldnt find anything.

Is it possible to open the Ship Menu for Region change with a hotkey? 

It just gets tedious always looking for the Dock in the different regions, especially if one has the map super small like me.

**Comment by SpiderlingJr** [comment]
wrong repo, sorry

**Comment by Ephenia** [comment]
You know, this could have very well easily been a suggestion.
