### ISSUE TITLE
"Disable all notifications" disables the Refresh in Quests

### ISSUE THREAD

**Issue by Cransonjast295** [Ephenia/Pokeclicker-Scripts#27]
While playing the game, I had just added the Additional Visual Settings into my file, and turned on the option to disable all notifications. Then went to go refresh my quests and no matter what I did, the prompt to ask if your sure if your sure does not pop up, and therefor not letting you reset quest. 

I did a little testing and it is only when "Disable all notifications" is on. Does not matter if it is a free or paid refresh. 

I am using Brave as a browser to play the game, I do not know if this would have any effect on this issue.

**Comment by Ephenia** [comment]
Duplicate issue of [this issue here](https://github.com/Ephenia/Pokeclicker-Scripts/issues/5).
