### ISSUE TITLE
[Bug][Auto Quest Completer]Do not auto enable all quests anymore

### ISSUE THREAD

**Issue by Ignorance001** [Ephenia/Pokeclicker-Scripts#272]
Hello,

For a few weeks the script has not been working properly anymore on my end. I am using the desktop app.

At the refresh of the quests, it does not enable all 10 quests anymore but a (random) number of it. While the button is toggled "on", it is not possible to enable the remaining quests. However when the button is switched to "off", it is then possible to manually enable those, meaning the initial limit of quests is still ignored.

Also sometimes when the button is toggled "on" while still having quests in the queue, it ignores them and auto-refresh.

**Comment by TEKami13** [comment]
I had the kind of the same problem, and it seems like there's a way to clear the filter.
The second comment on this https://github.com/Ephenia/Pokeclicker-Scripts/issues/180

**Comment by Ignorance001** [comment]
It seems the new update of the game has solve this issue, and some latency too.
