### ISSUE TITLE
[Feature Request] Increased auto speed for full challenge on

### ISSUE THREAD

**Issue by Arkshija** [Ephenia/Pokeclicker-Scripts#28]
I started a run with all the challenges ON, the game is grindy and I like it. But would be cool to have some extra use for the achievement bonus.

Would be possible to add a script to make the achievement bonus affect also auto attack speed? That way playing with every challenge ON would be much more interesting and the achievement bonus would be much more useful without being too op or cheaty. 100% achievement bonus = x2 auto at speed.

**Comment by Ephenia** [comment]
Changing attack speed wouldn't be possible without a modification of the game's source code, so this wouldn't be possible through the use of scripts. Forking or modifying the game's source code is also something that I do not plan to do personally myself. 

The minimum (tick) delay on anything and everything is 0.05s (50ms).

**Side note and for general reading:** I'm also aware that there are modified versions of the games that exist (albeit outdated), but this was also a big part of my motivation to create these scripts in the first place. While they do compromise the limitations of what can be done through them in relation to the game, the major upside to them is that they aren't as likely to just break with future updates of the game and will be compatible with them.
