### ISSUE TITLE
[Bug] Dungeon list not appearing

### ISSUE THREAD

**Issue by Cissamannen** [Ephenia/Pokeclicker-Scripts#287]
Hi.

Using the windows client, version 1.2.0 and updated to game 1.10.10 the additional visual script seems to no longer load the dungeon list shortcut. Tried looking in the script itself but nothing seemed out of the ordinary at first glance.

It worked on 1.1.0 on game 1.10.09. Seems to be the only thing broken.

EDIT: Yes I have ran the fixerupper to test with that too. :)

**Comment by elrandira** [comment]
Work-around:
In Tampermonkey, select Additional visual settings > Edit
![image](https://user-images.githubusercontent.com/82774041/230029406-2631bdab-c27e-4852-8f5c-fb3467a1e881.png)

replace line 317 with:
`if (townData.constructor.name == 'DungeonTown' && townData.dungeon != null) {`

save and reload the pokeclicker page
