### ISSUE TITLE
Problem with automine threshold

### ISSUE THREAD

**Issue by Arkshija** [Ephenia/Pokeclicker-Scripts#29]
The number input has a weird behaviour and we cant type big numbers. I can type 9999, when typing the 5th 9 the number becomes  99.999 and with the 6th it turns into 100.

I think it may be due the locale number format (dots and comas for thousands or decimals) (the local language is EU Spanish) . Maybe when doing the .toLocaleString ¿?

**Comment by Ephenia** [comment]
This issue should be fixed as of commit c0de8a2d68874cb43a47d91d322d1a595aef7911.
