### ISSUE TITLE
Seasonel Event

### ISSUE THREAD

**Issue by Cxrent1** [Ephenia/Pokeclicker-Scripts#297]
Hi, I was completing the pokedex with the seasonal pokemon when I saw the some of the pokemon were not loaded.
And I also couldn't find Grinch Celebi, it doesn't appear in the donjon pokemon list.
![seasonal event](https://user-images.githubusercontent.com/130925998/232332077-540ccb79-e1d8-473a-9ad5-03b774c3178a.png)
![grinch celebi](https://user-images.githubusercontent.com/130925998/232332131-01e40c3a-d32a-463f-8615-424ae14300bf.png)

**Comment by Ephenia** [comment]
I think this was fixed as of https://github.com/Ephenia/Pokeclicker-Scripts/pull/305

Closing.
