### ISSUE TITLE
Scripts Suddenly Not Working

### ISSUE THREAD

**Issue by RaisonforBeing** [Ephenia/Pokeclicker-Scripts#30]
I've had the issue where one random script wasn't working but I didn't mind it much. However, when I opened the game today, none of the four main scripts (underground, autoclicker, auto hatch, and auto farm) weren't working. After opening and closing the game for around 15 minutes, I was only able to run auto hatch and auto farm. Autoclicker and underground never worked. I reinstalled the app.rar thinking that might be it (idk technology that well) but nothing changed. The game worked perfectly fine last night.

**Comment by Ephenia** [comment]
Are you using the modified version of Pokeclicker Desktop that I had released?

**Comment by Ephenia** [comment]
Marking as a duplicate (issue https://github.com/Ephenia/Pokeclicker-Scripts/issues/19).
