### ISSUE TITLE
Autoclicker is broken

### ISSUE THREAD

**Issue by Xross98** [Ephenia/Pokeclicker-Scripts#303]
I've tried the Scriptfixerupper and it didn't work, I can't activate/deactivate either the clicker, auto gym or auto dungeon and whilst the script is active the Pokemon don't take damage from idle dps. I do all challenges so Idk about regular clicks.

It also seems to break the weather changer as I can't change weather either whilst the autoclicker script is active.

I haven't noticed any issues with other scripts though.

![ScreenShot_20230424134452](https://user-images.githubusercontent.com/106489040/234000388-0b96f302-0186-42f4-8062-215b98ab545d.png)

**Comment by Llonar** [comment]
Same problem here, I would add my farm is frozen actualy.
![image](https://user-images.githubusercontent.com/107852622/234189257-68211336-feed-4bb9-9d1e-af9e1d529e73.png)

**Comment by Llonar** [comment]
Does it help??
![image](https://user-images.githubusercontent.com/107852622/234206799-b7438c3d-0b44-4d25-a29e-6644033710cc.png)

**Comment by Xross98** [comment]
> What OS and platform are you using? Are there any error messages in the console?
> 
> The frozen battle item timer implies something went wrong while loading the game, but I haven't run into any issues like that while testing. Also not sure why the statistics are splitting onto separate lines.

I'm on Win10 using the client, not browser, also not sure how to open this console? I'm pretty tech illiterate, I should probably take a course or something tbh, I get no popups or anything so idk.

**Comment by Xross98** [comment]
Installing the newest version did fix it, so it must have been that, TY for the help.

**Comment by Llonar** [comment]
> Installing the newest version did fix it, so it must have been that, TY for the help.

Same here, it's all ok now, ty for the help :)

**Comment by TirOFlanc** [comment]
Hi,

I had the same problem with version 1.1.

So I installed version 1.2 and everything is fine.

However, version 1.2 (without the scripts) is weird for me.

The game window has no border or title bar.

This means that I can't resize the game window or move it or minimize it or maximize it or close it.

Do you have any idea where this can come from, a trick to fix the problem.

I am using the desktop application under Windows 7 x64

Thank you for your help.

**Comment by TirOFlanc** [comment]
Yes, without the scripts, vanilla mode, without the modified app.asar.
