### ISSUE TITLE
Pokerus mode does not work properly.

### ISSUE THREAD

**Issue by StanleyAlbayeros** [Ephenia/Pokeclicker-Scripts#304]
Pokerus mode seems to only do the following:
- prioritize the queueing the starter as soon as it is available.
- choose any non pokerus mon and put it after the starter.

Since the types have to be the same between the spreader and the target, this almost never works and it would take ages to spread this way. I propose the following solutions, maybe i'll get to fixing myself sometime next week:

- [Easy] pokerus mode still prioritizes starter, but uses your filtering. This way, you could set up all, grass, uninfected as a filter in the app, and your starter would spread pokerus automatically. Looking at the code this would be a... 1 line change?
- [Hard] Pokerus mode takes the list of uninfected mons, and pairs up infected pokemon with the correct typing, making sure there's at least 1 infected at all times with at least one matching type.
-

**Comment by Ephenia** [comment]
Yeah, it's outdated since it's a long time since I had wrote it at the time when PKRS worked differently.

Someone will need to update all of it and make it better again.

**Comment by drkztan** [comment]
As usual work piles up so I haven't been able to get to this. Mind sharing how to setup the dev environment so I can jump right in when I get the time? :) I'm more of a traditional tech stack dev (FW, Hardware, low level) so not too familiar with web stuff

**Comment by elrandira** [comment]
if you play in browser using TemperMonkey it is quite easy.
You just need to open a copy of the script you want to modify in your favorite text GUI (notepad++...). You modify the script according to your needs.

For testing, you click on TemperMonkey icon > select the script > edit and paste your code in the new window.
![image](https://github.com/Ephenia/Pokeclicker-Scripts/assets/82774041/0ab76e7d-82df-4879-b340-8afb71c02471)

you can then refresh your pokeclicker tab to start testing and use the console tab of the dev tool to debug (Ctrl + Shift + I on firefox)
