### ISSUE TITLE
AutoGym "All" issue

### ISSUE THREAD

**Issue by TirOFlanc** [Ephenia/Pokeclicker-Scripts#309]
For my part, I no longer have the "All" option in the Gyms drop-down menu.

![image](https://github.com/Ephenia/Pokeclicker-Scripts/assets/56934692/0b281565-e2b1-4b14-9f12-c83d18fe97bc)

**Comment by TirOFlanc** [comment]
So it will no longer be possible to automatically do the whole league or will another system be implemented soon ?

**Comment by TirOFlanc** [comment]
I feel like we didn't understand each other.

The point of the "All" option was not to do the different gyms in a row, and in a way, effectively, play in the player's place, but to do, for example, all five Pokémon league trainers in a row and in a loop, instead of just choosing one at a time.

Did we agree?

**Comment by TirOFlanc** [comment]
I'm not talking about this feature : https://github.com/Ephenia/Pokeclicker-Scripts/pull/240
![image](https://github.com/Ephenia/Pokeclicker-Scripts/assets/56934692/6adfaa3c-5843-4bc4-ac5e-fc6108cfccda)

**Comment by Ephenia** [comment]
I just wanted to add that the main reason why I had initially put in the `All` for Auto Gym was to be a thing that could help with achievements, but also kinda making it easier to battle through the E4 members. I didn't really see why else anyone would use it except for the achievement part mostly, but yeah. If Auto Achievements can get added sometime down along the line, then I don't think it's too bad of a loss or anything.
