### ISSUE TITLE
[Bug] Lost management of scripts.

### ISSUE THREAD

**Issue by Ignorance001** [Ephenia/Pokeclicker-Scripts#310]
Hello,

On the desktop client version, in the settings, I do not have the Scripts tab anymore. Therefore I can't manage which script to use or not.
The scripts previously activated and new ones that are implemented (such as the one to grow berries over night) are stilll running.

Did the script management tab move somewhere else or do I have to do something to fix this ?

**Comment by TirOFlanc** [comment]
Same problem.

**Comment by Ignorance001** [comment]
So after losing all the scripts in game, I redownloaded the app.asar file, replaced the previous one in the proper folder.
And now it recovered both the scripts and the tab management in the settings.
