### ISSUE TITLE
Broken Questlines and Events

### ISSUE THREAD

**Issue by Xross98** [Ephenia/Pokeclicker-Scripts#314]
Some Questlines don't work while scripts are being used, the only one I know of so far is "Recover the Precious Egg!" in Sinnoh. Although the quest can be accepted, some parts of it cannot be completed. Turning Scripts off and reloading fixes this. 

Also the "Golden Week" event, when toggled on in the event menu, doesn't spawn Rose Bulbasaur in Flower Paradise, I haven't experienced any issue with other Events up to Sinnoh though so this may be the only one.

**Comment by Xross98** [comment]
Strike that last part, I didn't know you needed to clear Flower Paradise 10 times for Rose Bulbasaur to spawn, **just the Questline issue, no issues with events.**

**Comment by Xross98** [comment]
> Which part of the quest doesn't work?

Part 9 - "They're using Parasect to navigate the Eterna Forest. Clear out a Parasect and they should get trapped!" I defeated Parasect a few dozen times and it never registered until I used no scripts, I don't know if any other parts have this same issue though since I completed the quest with all the scripts off, mb.

**Comment by Chalo90** [comment]
Hi, I just came here to report this indeed the Part 9 - "They're using Parasect to navigate the Eterna Forest. Clear out a Parasect and they should get trapped!" is indeed broken, was using the client version, I sent the save to the web and managed to complete the quest on the 1st parasect i killed.

**Comment by elrandira** [comment]
so is it the game itself or the autoquest script? If it is the first, it should be reported on the proper github

**Comment by umamaistempo** [comment]
@Chalo90 do you have a save that is stuck at that part for me to test a fix, please ? Thanks

**Comment by Chalo90** [comment]
I can provide it tomorrow as i am not in the pc at the moment

**Comment by umamaistempo** [comment]
Found a backup of mine and just tested, the PR #316 successfully fixes this problem. Please give the PR a 👍  so it can be merged
