### ISSUE TITLE
Do not auto-load extreme scripts

### ISSUE THREAD

**Issue by AkumaNoTsubasa** [Ephenia/Pokeclicker-Scripts#32]
I just broke my save game by giving my gyarados over 800 proteins while I only wanted to max out the normal max value. This change was made without any information. 
Please do NOT auomatically load such extreme scripts.
While Autohatchery, Autodungeon, Autoclick, Auto Farm, Auto Dungeon/Gym is all nice and feel like they have to be in the game, stuff like the unlimited oak items or now unlimited (?) proteins just break the game and fun.

**Comment by Ephenia** [comment]
This is not my fault nor problem whatsoever, in all honesty.

There's a disclaimer at the top of the [README.md](https://github.com/Ephenia/Pokeclicker-Scripts#readme) that explicitly states for you to back up your saves before using any scripts here. You should be doing this regularly anyway with or without the use of scripts, regardless if you care that much about your save(s). On top of that, [you should have carefully read and paid more close attention to how the client edit actually works before ever even downloading and using it](https://github.com/Ephenia/Pokeclicker-Scripts/releases/tag/v1.1):

- > **Every subsequent launch after initial launch, the client will check for updates on every one of my scripts that would be inside `...\PokeClicker\pokeclicker-desktop\recourses`, and will update and load them silently if there are any updates/changes made to any of my scripts that I've made.**
- > **The client will also grab and download any new scripts as well that I may add as well in the future here.**
- > **This also means that you may block/override loading of my scripts as well, all you would have to do is create an empty JavaScript file that would correspond to the script that you wouldn't like loaded and place it inside `...\PokeClicker\pokeclicker-desktop\recourses\scripts`. Same logic applies to modified versions of my scripts, of course.**

If you paid more attention like most people, you wouldn't be the first one that's actually legitimately giving me crap here for no real reason whatsoever.

Don't like how something works? Don't use it.

This goes for you and anyone who is going to complain and or bark at me. This is all free and unpaid work, literally a project out of pure passion. Did I have to create this or share any of my work in the first place? No, so be more appreciative of what's being given to you.
