### ISSUE TITLE
[Feature request] Auto Safari Zone / Easy Safari Zone

### ISSUE THREAD

**Issue by K0STYURIK** [Ephenia/Pokeclicker-Scripts#325]
As of v0.10.12 there are new achievements in PokeClicker - pick up 100 items in the Safari Zone, throw 1000 rocks, throw 1000 bait, walk 10000 steps, reach Safari Zone level 30. All those tasks are incredibly tedious, require manual navigation on Safari Zone location map and worth like multiple weeks to complete. (By the way, both Pinsir and Scizor Mega Stones are locked behind Safari Zone items)
Is there any way to either automate the Safari Zone process with java scripts (like with dungeons bosses and chests), or at least set the catch rate in the Safari Zone to 100% and flee rate in the Safari Zone to 0%)?

Thanks in advance!

**Comment by thread123** [comment]
Something for the catch rate in the Safari zone would be really helpful.

**Comment by elrandira** [comment]
see https://github.com/Ephenia/Pokeclicker-Scripts/pull/331

any tester of this code is welcome
