### ISSUE TITLE
[Bug] Auto hatchery

### ISSUE THREAD

**Issue by NicoTine34** [Ephenia/Pokeclicker-Scripts#333]
Auto hatchery is not working after the update.
![image](https://github.com/Ephenia/Pokeclicker-Scripts/assets/30953411/e26e29f8-dfd4-4159-8206-11fa7b71467a)

**Comment by NicoTine34** [comment]
Auto-mine too if you dont have restores.

**Comment by NicoTine34** [comment]
Im using last desktop version with all scripts. No errors in console. 
Im just turning the Auto Hatch On and the eggs are stuck in hatchery. I need to click Off then On to hatch them.

**Comment by cayorangel** [comment]
having the same issue here

**Comment by cayorangel** [comment]
when i load the game, it is on

![image](https://github.com/Ephenia/Pokeclicker-Scripts/assets/128825503/df9aa9cc-2663-4c6e-8dd3-4be4040a5d2d)

the hatchery looks like this

![image](https://github.com/Ephenia/Pokeclicker-Scripts/assets/128825503/7b6f4e11-f7d3-4e95-a6e8-c79e4591a305)

then i have to turn off and on to work again everytime, it doesn't fix it

![image](https://github.com/Ephenia/Pokeclicker-Scripts/assets/128825503/f439cabb-e4f2-459d-aced-3438b16a9388)

that's my console log

![image](https://github.com/Ephenia/Pokeclicker-Scripts/assets/128825503/2e411496-e4c8-42d0-a713-735ab24e41c7)
![image](https://github.com/Ephenia/Pokeclicker-Scripts/assets/128825503/ac1c688e-7835-4ef8-8892-1baf1a855d8e)

and the screenshot when i try to run the code in console

![image](https://github.com/Ephenia/Pokeclicker-Scripts/assets/128825503/fc340a55-1bf6-45cb-974d-86f11fa69546)

hope it helps, i know nothing about coding, just love the game

**Comment by cayorangel** [comment]
disabling Perky Pokerus Pandemic worked
