### ISSUE TITLE
[Feature Request] Auto Best Vitamins

### ISSUE THREAD

**Issue by RuyoTramp** [Ephenia/Pokeclicker-Scripts#347]
If you go to the wiki, under each pokemon there is a best vitamins distribution. 
My request is making a script that buys the vitamins and puts the best in each pokemon, even if they already have vitamins.
I dont know if  the wiki has an api that lets you extracts the number, but let me know if it can be done.

![image](https://github.com/Ephenia/Pokeclicker-Scripts/assets/98341183/e082c5f7-7bae-4ee6-8e83-ea83e2d1d987)

**Comment by Synogun** [comment]
latest visual script adds a scale icon in the all vitamins modal, next to the Pokémon names, isn't auto but it helps a lot already

**Comment by RuyoTramp** [comment]
I didnt know that, then a apply all would do just fine
