### ISSUE TITLE
Last commit (Merge pull request #381) make almost everything stop working

### ISSUE THREAD

**Issue by Orbital-fury** [Ephenia/Pokeclicker-Scripts#386]
Since the last commit (https://github.com/Ephenia/Pokeclicker-Scripts/commit/b6f0adb5c89c40effa5f99abc54eae3bdb3d25e7), almost every script seem to not be loaded.
I am playing pokeclicker on brower, last version of firefox, W11, using tampermonkey.

I had to disable auto-update on tampermonkey and reload the previous version of all scripts I used (all classic scripts and only 1 custom: auto quest completer).

It seems only enhanced auto clicker was still working.
For sure: additional visual settings doesn't work for me. Same with auto battle items, enhanced auto hatchery, simple auto farmer. I didn't check the others.
I guess the scripts are not loaded because I can't see the button it should create.

Am I alone with this problem ?

**Comment by ToasterGod** [comment]
yeah I'm experiencing the same issues
although I don't know how to roll the broken scripts back

**Comment by CrazyPieGuy** [comment]
I am having issues with the Auto Hatchery, Auto Farmer, and Auto Miner.

**Comment by Lapbunny** [comment]
Same issue here - latest version of Chrome, W10, tampermonkey.
