### ISSUE TITLE
enhancedautoclicker not working anymore (v0.10.20)

### ISSUE THREAD

**Issue by KlayFrog** [Ephenia/Pokeclicker-Scripts#396]
Since the lastest update (v0.10.20) there is an error message after choosing a save:
"The 'enhancedautoclicker' userscript crashed while loading. Check for updates or disable the script, then restart the game."
Auto Click, Auto Dungeon and Auto Gym doesn't work anymore (other scripts don't seem to be impacted afaik)

**Comment by Realswitzer** [comment]
```
VM399:1076 Uncaught TypeError: player.route is not a function
    at EnhancedAutoClicker.hasPlayerMoved (<anonymous>:1076:34)
    at EnhancedAutoClicker.calcClickStats (<anonymous>:971:18)
    at <anonymous>:957:76
VM399:632 Uncaught TypeError: player.town is not a function
    at EnhancedAutoClicker.canStartAutoDungeon (<anonymous>:632:136)
    at EnhancedAutoClicker.toggleAutoDungeon (<anonymous>:334:31)
    at HTMLButtonElement.<anonymous> (<anonymous>:203:109)
```
Any script relying upon `player.route` and `player.town` needs fixing

```
Search "player.(route|town)" > 15 results - 3 files

catchfilterfantasia.user.js
enhancedautoclicker.user.js
custom/autosafarizone.user.js
```

**Comment by Realswitzer** [comment]
Found a fix, will make a PR.

**Comment by VincentPS** [comment]
I love this community

**Comment by Realswitzer** [comment]
After testing everything I could think of, all affected scripts should be functional again with #397. If there are any more problems, feel free to note broken scripts on the PR.

**Comment by Apganda617** [comment]
Hi Desktop Version still don't work for me.
