### ISSUE TITLE
Hatchery sorting

### ISSUE THREAD

**Issue by toonvdijck** [Ephenia/Pokeclicker-Scripts#4]
Following the 0.8.10 update, there is a problem with the sorting list in the hatchery.
It doesn't follow "sorted by" anymore

**Comment by Ephenia** [comment]
Auto Hatchery should be fixed up and all set as of fe7c084e6b5a8fc63f25c29f0e80254f1ee4d3e4. Please feel free to test it out and if there are any issues then feel free to let me know!
