### ISSUE TITLE
New update breaks some things!

### ISSUE THREAD

**Issue by shibii1111** [Ephenia/Pokeclicker-Scripts#43]
Like an idiot I updated my game... If you read this and didn't update yet, wait!

It seems to mainly break additionalvisualsettings.js as it is adding infinitely the options in the menu and cogs all over the screen. That's all I noticed so far. I tried to reinstall the game, but it seems to reinstall the latest version. The easy temp fix for now is to close and reopen the game every 5mins or so.

![pokeclicker bug](https://user-images.githubusercontent.com/17680533/160887530-559de67f-c672-4d8a-8b52-45a18cd4e780.png)

**Comment by overlordbossk** [comment]
It also looks like you can't have all the Oak Items equipped at same time if you click to change your loadout.

**Comment by Organ1zedCha0s9** [comment]
Yeah, it is an issue.. For the moment until fixed, you could just delete additionalvisualsettings.js from the scripts folder. I tried looking at the code for the file but I don't see a reason it would be creating infinite icons and duplicating the menu.

**Comment by shibii1111** [comment]
I wish we could, but it keeps reinstalling it by itself and same if we change it. It's part of the whole thing

**Comment by shibii1111** [comment]
Semi quick fix if anyone is reading this and is bothered:

open it in your editor(VSCode, notepad, whatever) and comment those lines :
24 : quickSettings.src = ....
29 to 60 : 

```
document.querySelectorAll('tr[data-bind*="currencyMainDisplayReduced"')[0].outerHTML += `<tr>
    <td class="p-2">
        <label class="m-0">Show wild Pokémon Name</label>
    </td>
    <td class="p-2">
        <input id="poke-name" type="checkbox">
    </td>
</tr>
<tr>
    <td class="p-2">
        <label class="m-0">Show wild Pokémon Defeated</label>
    </td>
    <td class="p-2">
        <input id="poke-defeat" type="checkbox">
    </td>
</tr>
<tr>
    <td class="p-2">
        <label class="m-0">Show wild Pokémon Image</label>
    </td>
    <td class="p-2">
        <input id="poke-image" type="checkbox">
    </td>
</tr>
<tr>
    <td class="p-2">
        <label class="m-0">Show Pokémon Health</label>
    </td>
    <td class="p-2">
        <input id="poke-health" type="checkbox">
    </td>
</tr>`
```


then set the file to read only.

**Comment by Stivenzino** [comment]
> Semi quick fix if anyone is reading this and is bothered:
> 
> open it in your editor(VSCode, notepad, whatever) and comment those lines : 24 : quickSettings.src = .... 29 to 60 :
> 
> ```
> document.querySelectorAll('tr[data-bind*="currencyMainDisplayReduced"')[0].outerHTML += `<tr>
>     <td class="p-2">
>         <label class="m-0">Show wild Pokémon Name</label>
>     </td>
>     <td class="p-2">
>         <input id="poke-name" type="checkbox">
>     </td>
> </tr>
> <tr>
>     <td class="p-2">
>         <label class="m-0">Show wild Pokémon Defeated</label>
>     </td>
>     <td class="p-2">
>         <input id="poke-defeat" type="checkbox">
>     </td>
> </tr>
> <tr>
>     <td class="p-2">
>         <label class="m-0">Show wild Pokémon Image</label>
>     </td>
>     <td class="p-2">
>         <input id="poke-image" type="checkbox">
>     </td>
> </tr>
> <tr>
>     <td class="p-2">
>         <label class="m-0">Show Pokémon Health</label>
>     </td>
>     <td class="p-2">
>         <input id="poke-health" type="checkbox">
>     </td>
> </tr>`
> ```
> 
> then set the file to read only.

What do you mean by "comment"? I tried but it doesn't change anything. Could you just give me your file, maybe?

**Comment by shibii1111** [comment]
> Ok I figured it out, but commenting them will disable autoclicker tho. Any solution on this?

sorry for the long time response, actually it happens to me too, I noticed that when you open the game, you should wait about 10secondes before clicking on your save, but I end up rebooting the game usually 4-5 times then it's all good and I'm leaving it open forever haha

**Comment by Iamthebestintheworld222** [comment]
That happened to me too.

**Comment by KarmaAlex** [comment]
Better way of fixing the options spam is by editing only line 249
`if (typeof gameState != 'undefined') {`
and changing it to 
`if (typeof gameState != 'number') {`
read only still required of course.
The rest of the file still doesn't work though, I might look into fixing it later seen as the dev has been inactive recently.
