### ISSUE TITLE
Auto Farmer doesn't work

### ISSUE THREAD

**Issue by UltraLuigi** [Ephenia/Pokeclicker-Scripts#44]
The issue is as stated in the title, more precisely there are no buttons for it anywhere on the farm screen. I have confirmed that the script is in the scripts folder (and have relaunched the game multiple times). The rest of the scripts I'm using work fine, it's just the farmer that's broken.

**Comment by shibii1111** [comment]
Mine still works and as I explained on my own ticket, sometimes you have to wait 15-30sec before clicking on your save. Probably something takes longer than usual to load and the farm script is coming later in the loading order and you skip it by opening your save right away. That's my 2 cents, we didn't get any feedback from ephinia, so take it with a grain of salt.

**Comment by UltraLuigi** [comment]
> Mine still works and as I explained on my own ticket, sometimes you have to wait 15-30sec before clicking on your save. Probably something takes longer than usual to load and the farm script is coming later in the loading order and you skip it by opening your save right away. That's my 2 cents, we didn't get any feedback from ephinia, so take it with a grain of salt.

I gave it a good 5 minutes and there's still no auto farmer.
