### ISSUE TITLE
Having a settings button spam across my screen.

### ISSUE THREAD

**Issue by Nunn2962** [Ephenia/Pokeclicker-Scripts#45]
![image](https://user-images.githubusercontent.com/103240037/162373791-0127ecda-06fb-42c0-b31c-a6d022ed1428.png)

Started on it's own today after I restarted the client because of lag.

**Comment by sickhippie** [comment]
Getting the same issue.  Console throws `Uncaught TypeError: Cannot read properties of undefined (reading 'prepend')`.

Issue seems to be this line: `document.querySelectorAll('tbody[data-bind*="Object.values(NotificationConstants"')[1].prepend(notifiyHTML)`

**Comment by KarmaAlex** [comment]
This has been fixed as of 5 days ago
