### ISSUE TITLE
Seasonal events stopped working

### ISSUE THREAD

**Issue by Denai85** [Ephenia/Pokeclicker-Scripts#46]
Because of the new egg event being added, the seasonal event script is not working anymore.
I added it a few hours before the update and it was running fine, booted the game up after running a few errands and it no longer seems to be working.
Thanks for this list by the way, changed the game in a major way for me, made it much more enjoyable.

**Comment by Ephenia** [comment]
The script should be fixed and working again as of commit 444d7413069e86b87d1b231b09b956f0e0ed816f ❤️
