### ISSUE TITLE
Is it safe to update to 0.9?

### ISSUE THREAD

**Issue by Stivenzino** [Ephenia/Pokeclicker-Scripts#47]
Pretty much, title.

**Comment by KarmaAlex** [comment]
Currently it is not. I am working on fixing the scripts myself, expect an update either today or tomorrow

**Comment by Stivenzino** [comment]
Any news? @KarmaAlex 
What problem are there, actually?

**Comment by KarmaAlex** [comment]
The scripts fail to load sometimes on the desktop client, visual additions is broken as so is the events script because of the new one. I've made the pull request, waiting for it to be approved
