### ISSUE TITLE
Infinite Seasonal Events a little broken in 0.9.1

### ISSUE THREAD

**Issue by UltraLuigi** [Ephenia/Pokeclicker-Scripts#49]
The christmas and ephenia's gift events are both permanently active. Activating either one will add a second copy of the roaming pokemon to the list. When deactivating the christmas event, the first copy of the pokemon get removed, but not the second. For ephenia's gift, the pokemon never get removed from the list. 
Here's a screenshot of what happened after a bit.
![image](https://user-images.githubusercontent.com/35938600/163746992-a8bc2ee4-1c06-409b-9c3f-d28aac9e3b37.png)
After deactivating the christmas event:
![image](https://user-images.githubusercontent.com/35938600/163747101-696806bd-3986-46ee-9146-3e5135f1c502.png)

Using ctrl-r (note I'm on the desktop app) will reset the ribombee to one (two if I reload while the event is active), and has no effect on the christmas pokemon.

**Comment by KarmaAlex** [comment]
Yeah the events script will probably need to be rewritten as it is a bit broken, i'll look into it

**Comment by KarmaAlex** [comment]
This should have been fixed in the latest update, be sure to let me know if you find more issues
