### ISSUE TITLE
Resetting quests

### ISSUE THREAD

**Issue by Biosaur1** [Ephenia/Pokeclicker-Scripts#5]
No popups will popup on the website while using scripts. This means you can't reset the quests for a refresh or anything else that has a popup to confirm. This only happens when you have disable notification setting checked. If you could have a setting where you can do both, that would be great.

**Comment by Ephenia** [comment]
This is finally fixed as of commit 0d89e816eb89feb5edd34254229a1549e60e369f ❤️
