### ISSUE TITLE
A bug with autodungeon

### ISSUE THREAD

**Issue by RuyoTramp** [Ephenia/Pokeclicker-Scripts#50]
There is a bug with auto dungeon that if the boss is the top left corner, the bot keeps jumping from the left to bottom of the boss, this happen to me in the iron island on farming mode, I don't know if in other dungeon this would happen.
Not a game breaking bug, but something to report
![Untitled](https://user-images.githubusercontent.com/98341183/164195218-0f770375-4398-49c7-b442-30e6910ad579.png)
.

**Comment by KarmaAlex** [comment]
I encountered this bug too a couple of times, I'll attempt to fix it although it's hard to test since it's rare for the boss to be in a corner.

**Comment by KarmaAlex** [comment]
This should have been fixed as of the latest update since the algorithm has changed

**Comment by RuyoTramp** [comment]
i'll pay attention to that
