### ISSUE TITLE
Simple Weather Changer doesn't seem to affect weather based encounters or evolutions.

### ISSUE THREAD

**Issue by VoltageMiner** [Ephenia/Pokeclicker-Scripts#55]
Changing the weather using the Simple Weather Changer doesn't seem to affect weather based encounters or evolutions. For example, leveling up a Cherrim (overcast) to 'evolve' into a Cherrim (sunshine) doesn't work despite the weather set to sunny. As for Castform, I was missing Castform (rainy) but I was able to catch it normally in natural weather, but I couldn't get the Castform (snowy) I was missing to appear after setting it to the various snow related weathers. This issue probably affects Sliggoo to Goodra's Rain or Fog based evolution too, but I can't test it.

**Comment by KarmaAlex** [comment]
I've implemented a fix for this in the next commit, should be approved soon.

**Comment by VoltageMiner** [comment]
Issue resolved.
