### ISSUE TITLE
Infinite Seasonal Events links to missing image assets due to a previous update of Pokeclicker renaming some event pokemon.

### ISSUE THREAD

**Issue by VoltageMiner** [Ephenia/Pokeclicker-Scripts#56]
The Infinite Seasonal Events script appears to be linking to various pokemon such as "assets/images/pokemon/-1.png", -3.png, etc. but these images have since been renamed in the more recent versions of Pokeclicker which causes a broken image icon to appear in the UI.

**Comment by KarmaAlex** [comment]
This should be fixed in the next commit as well.

**Comment by VoltageMiner** [comment]
Issue resolved.
