### ISSUE TITLE
Auto Gym Broken

### ISSUE THREAD

**Issue by ZargoGames** [Ephenia/Pokeclicker-Scripts#59]
The Pokeclicker update that released this morning seems to have broken the auto gym function of the autoclicker. So far it seems like the rest of the script is working fine, but auto gym does nothing now.

**Comment by kennedyl94** [comment]
once you buy a flute it broke every timer. So pokemon attacks wouldn't work, only click attacks, and dungeon timers would not count down.
Also it would prevent saving.

**Comment by Kiyarazzz** [comment]
I haven't bought any flute, but the autoclicker is no longer working. Yes only click attacks. 
I can download saves. 

Anyway, thanks for all the work Ephenia, KarmaAlex and everyone. I have been enjoying the scripts.

**Comment by ZargoGames** [comment]
> once you buy a flute it broke every timer. So pokemon attacks wouldn't work, only click attacks, and dungeon timers would not count down. Also it would prevent saving.

I haven't experienced that, and I've bought every flute. The only issue I'm having is the auto gym not working.

**Comment by KarmaAlex** [comment]
> The Pokeclicker update that released this morning seems to have broken the auto gym function of the autoclicker. So far it seems like the rest of the script is working fine, but auto gym does nothing now.

Already fixed this, will be coming in the next commit


> once you buy a flute it broke every timer. So pokemon attacks wouldn't work, only click attacks, and dungeon timers would not count down. Also it would prevent saving.

As for this i've been able to buy flutes just fine, if it keeps happening after the update later today then open your own issue. If you're on the desktop version try to disable the events script and see if that fixes it,

**Comment by Hyperion505** [comment]
> Already fixed this, will be coming in the next commit

After updating the script, Auto gym still wont function.
Refreshed the page, disabled/enabled the script, tried  1 through 5. Got nothing, am I missing anything?
Auto Dungeon and normal Auto Click works.

**Comment by ZargoGames** [comment]
> > Already fixed this, will be coming in the next commit
> 
> After updating the script, Auto gym still wont function. Refreshed the page, disabled/enabled the script, tried 1 through 5. Got nothing, am I missing anything? Auto Dungeon and normal Auto Click works.

I don't think the commit has been applied yet

**Comment by Hyperion505** [comment]
> I don't think the commit has been applied yet

Ah my bad, wasnt sure if the latest commit was this one or not.

**Comment by Ephenia** [comment]
This should be fixed now as of commit 1126c69100ef43c7208ca129cbb41f70ae43f526 ♥
