### ISSUE TITLE
[New Feature] Being able to auto refresh quests

### ISSUE THREAD

**Issue by RuyoTramp** [Ephenia/Pokeclicker-Scripts#61]
So, I think that have an option to auto refresh quest when they are free, optional ofc, because if you didn't complete all quest by then, then you can move on.

**Comment by Ephenia** [comment]
Perhaps a filter for quests you aren't interested in completing, and have them auto refresh when you have completed all the ones that you're interested in?

**Comment by RuyoTramp** [comment]
that is a better option, but then again you are the smart one.

**Comment by Ephenia** [comment]
> Perhaps a filter for quests you aren't interested in completing, and have them auto refresh when you have completed all the ones that you're interested in?

Did some quick work and this is now implemented with what I had described here. You can check out commit 9aef169eaec0c29489521d506ac8bd23916ccedc for some more details. Enjoy ♥
