### ISSUE TITLE
Auto Gym no longer working after update

### ISSUE THREAD

**Issue by JoeStratton** [Ephenia/Pokeclicker-Scripts#64]
After the recent update the auto dungeon still works but auto gym does nothing

**Comment by Ephenia** [comment]
It is working, refer to issue https://github.com/Ephenia/Pokeclicker-Scripts/issues/62. You'll need to update.

Always remember to make sure that you check for the latest update of scripts.

**Comment by JoeStratton** [comment]
Ah so this is a versioning issue

**Comment by JoeStratton** [comment]
How do I know when there is a new update if the version doesn't tell me? Still seems like a bug. Thanks for the great work regardless
