### ISSUE TITLE
Infinite Seasonal Events in wrong order

### ISSUE THREAD

**Issue by generalm13** [Ephenia/Pokeclicker-Scripts#66]
Infinite Seasonal Events seem out of order on my end, They all work, but the images for most of them are under the wrong headers :P

![7e293c554b54f3d942d9aab73b7ed655](https://user-images.githubusercontent.com/1728512/166178624-fb8bcf27-3120-4252-aee2-2efce9b2d4d1.png)

**Comment by Ephenia** [comment]
This should be fixed and addressed as of commit b78aa1d066f31d7fbddd6eba4959b9fb25a2b46a.
