### ISSUE TITLE
autobattlefrontier: Automatically restart once no longer able to n-shot the enemy

### ISSUE THREAD

**Issue by Latecomerr** [Ephenia/Pokeclicker-Scripts#67]
Suggestion: Add an autobattlefrontier mode that simulates a defeat and restart once an enemy pokemon took more than n hits to defeat  
That way, the player does not need to figure out the optimal floor for themselves, and this would also be dynamic with other things happening to the battles (gems, breeding, level ups, flutes, battle items, etc.pp.)

Setting n = 1 would be one-shotting, setting n = 2 would be two-shotting etc.

Upper limit would theoretically be 59 (already beaten floor for an attack every 0.5 seconds, taking 29.5 attacks to defeat one enemy pokemon)

**Comment by Latecomerr** [comment]
User should be able to set n because different n are optimal for different purposes

n = 1 is optimal for farming total completed floors (achievements)  
n = 2 is optimal for battle points per second according to my math

**Comment by Ephenia** [comment]
I'll label this implemented as of commit dcf122d7a4455c44c0a6950798416ed8d427b954, but I'll still leave this opened for now as its partly implemented (n1 has been added).
