### ISSUE TITLE
weird glitch after i started using these scripts

### ISSUE THREAD

**Issue by Mega-Rayquaza-8121** [Ephenia/Pokeclicker-Scripts#74]
i don't even know if this is the problem of the quest completer or whatever.

after i started using the scripts i can't refresh or quit any of my quests, and my console says these error messages

<img width="359" alt="image" src="https://user-images.githubusercontent.com/62550729/167254126-8c83c60f-e642-435d-97d1-d3bcd3a57cf0.png">

i have enough money to refresh quest.

**Comment by Mega-Rayquaza-8121** [comment]
i should also add that i used inspect element to edit the game which sometimes causes weird shit to happen. but all i did was edit the underground things like bomb energy used, bomb efficiency, energy regen time and energy regen amount, which shouldn't really affect quests.

the weird problem also persists after i refreshed the page, closed and reopened the page. i only have not tried restarting the computer.

**Comment by Mega-Rayquaza-8121** [comment]
also, the issue did not start immediately but after a period of time it just didn't let me click it anymore.

**Comment by Ephenia** [comment]
This is likely due to [the long standing bug that occurs with using AdditionalVisualSettings](https://github.com/Ephenia/Pokeclicker-Scripts/issues/5) and disabling all notifications. It ends up breaking a lot of pop ups. I haven't really been bothered to fix this myself and rework/update the script.

**Comment by Mega-Rayquaza-8121** [comment]
thanks for clarifying but can i know why the auto quester just doesn't take the dungeon token or shiny pokemon quests?

<img width="608" alt="image" src="https://user-images.githubusercontent.com/62550729/167285105-c9db05b4-c050-4afe-9fca-c421f365d613.png">
it's covered but it's a shiny pokemon quest

<img width="602" alt="image" src="https://user-images.githubusercontent.com/62550729/167285121-f87c9fd4-7e19-412f-9454-0c1ed2948a36.png">
this one is dungeon token, and apparently also the mine x layers in underground quests, the auto quester just doesnt take

**Comment by KarmaAlex** [comment]
Likely caused by 9aef169eaec0c29489521d506ac8bd23916ccedc try clicking on them
