### ISSUE TITLE
[Feature Request] Buttons to open Underground and Farm Modals

### ISSUE THREAD

**Issue by keidrolis** [Ephenia/Pokeclicker-Scripts#76]
Currently, you can open Hatchery and Oak Items with the "List" buttons, a default feature of the game.

When you can see the map, you can click the Farm or Underground Entrance directly.

However, if you're farming a dungeon or a gym, you can't open these modals without using your keyboard.

Would it be possible to add buttons that would open these windows, and any other modals that are in later game? (I'm only in Kanto so far, so I don't know what other features have a pop up like these.)

**Comment by Ephenia** [comment]
I swiftly implemented most likely what you're looking for as of commit 23d8fbee2f195105401c1c66e4bbbbb6c4d50326. It's basically a new feature included in AdditionalVisualSettings script. By default, the Shortcuts menu will be displayed by default and will show before you've made enough progress in the game for it to actually display. You would still need the appropriate items to access the both the Underground as well as Farm.

**Comment by keidrolis** [comment]
That's awesome, thank you!
