### ISSUE TITLE
When notifications are disabled, some needed pop ups don't work

### ISSUE THREAD

**Issue by Kyle-Newton** [Ephenia/Pokeclicker-Scripts#77]
I have notifications disabled most times since I get the annoying small potion purchase or dungeon completion spams. 

However when all notifications are disabled I've noticed both Quest Refresh and Battle Frontier Quitting popups will not come up, meaning you need to reenable notifications first. 

Happens on both Chrome and Desktop versions.

**Comment by Kyle-Newton** [comment]
ah - while looking through all the issues I saw it back at #5

A suggestion might be just having options more other notifications that aren't available right now such as:

- purchases (think endless small restore alerts)
- dungeon completions
- underground items found
- Treasure hunter finding multiples
- you dig deeper...

**Comment by Ephenia** [comment]
This is now fixed as of commit 0d89e816eb89feb5edd34254229a1549e60e369f ❤️
