### ISSUE TITLE
[Feature Request] Hatchery - Split Auto Egg/Fossil into 2 buttons

### ISSUE THREAD

**Issue by keidrolis** [Ephenia/Pokeclicker-Scripts#78]
Not sure if anyone else shares this opinion, but I like to hold on to my fossils for daily deals in the Underground. Would it be possible to split the button into Auto Egg and Auto Fossil buttons? This way I can still automatically put eggs into Hatchery without using my fossils at the same time.

**Comment by Ephenia** [comment]
I remember I was going to separate them before, but I had completely forgot about it. It will get done and or it passes my approval for being an included feature.
