### ISSUE TITLE
[Feature Request] Enhanced Autofarming

### ISSUE THREAD

**Issue by miniblitz** [Ephenia/Pokeclicker-Scripts#79]
Some alternative options for the autofarmer, such as the ability to replant whatever was planted for combinations for mutations, the ability to set a timer that overlaps the autofarmer's 1 click per second default timer so that these mutations can take place for however long the plants are alive and mutating for, and just before they die the autoclicker harvests those berries that have failed to mutate, then returning to replanting the original berries. Would immensely help with berry farming and getting the different mutations.

**Comment by JohnyDL** [comment]
Auto farm to unlock berries would be nice too.... I'm guessing they'd need to be hard-coded.... I do prefer the berry helpers to the autofarm right now though
