### ISSUE TITLE
Little issue with auto gym

### ISSUE THREAD

**Issue by Steinzu** [Ephenia/Pokeclicker-Scripts#90]
When using auto-gym, 5 and ALL are inversed, 5 clears everyone while ALL only clears the last one

**Comment by JamesSampsan** [comment]
I actually noticed this earlier today, but prior to yesterday was working fine.

**Comment by Ephenia** [comment]
Probably new issue that comes with commit 0abe94d4e932aa70b4f4d5e69e7313eda6c7bc32. It's PR, so I haven't really tested it much myself and I consider anything I merge to be experimental. I will take a look now, however.

**Comment by Ephenia** [comment]
I fixed this now as of commit 0d673f712c5dcda4e4130e6422c9c6cc550b035d, there shouldn't be any issues with it. Please let me know if there are any issues with it though.

**Comment by Steinzu** [comment]
Works now, thank you! 👏
