### ISSUE TITLE
Auto-dungeon won't start boss fight

### ISSUE THREAD

**Issue by JesseRaen** [Ephenia/Pokeclicker-Scripts#91]
I've made sure I'm updated to the latest auto-clicker script, but even then I'm finding occasions where, when I'm set to B, the script will scour the entire dungeon, then stay locked on the same tile and not complete the boss. The only way to fix it is to let the timer run out, or turn off the autodungeon and start the fight manually.

I can't reproduce the issue at will, and it happens quite rarely, so not a huge problem, but I haven't seen anyone else mention it before.

**Comment by JesseRaen** [comment]
I can't reproduce it but I have found what causes it - it only happens when the boss tile is the last one uncovered in a dungeon. Instead of starting the boss fight it moves to that tile last then moves off it and waits in place.

**Comment by JamesSampsan** [comment]
I have found this happens if you change it from "Farm" or "Boost" mode to one or the other. I haven't had this problem if I keep the same one selected, but once I select a different one while the dungeon is running, it won't activate the boss tile.

**Comment by elrandira** [comment]
this happens as well if you don't give the focus on the tab running pokecliker
