### ISSUE TITLE
[Feature Request] Autobuy items

### ISSUE THREAD

**Issue by EugeneFabre** [Ephenia/Pokeclicker-Scripts#94]
Since item price increases evertime you buy one, it would be nice to have a script that lets you buy them automatically one by one so that you maximise the number of items you get for your money. Basically what the auto underground does for small restores already.
An auto use feature would be nice as well.

**Comment by Ephenia** [comment]
Already suggested here (Issue https://github.com/Ephenia/Pokeclicker-Scripts/issues/25)
